### ISSUE TITLE
ImportError: cannot import name 'SpikeSelector' from 'phylib.io.array'

### ISSUE THREAD

**Issue by zuhayousuf** [cortex-lab/phy#1000]
I installed phy, and when I ran 'phy template-gui params.py' this is the error I got. Any advice on how to resolve this?? Any help appreciated!!!

**Comment by rossant** [comment]
might be a version conflict, uninstall phy completely and reinstall the latest version following the [instructions](https://github.com/cortex-lab/phy#installation-instructions)

**Comment by zuhayousuf** [comment]
How do we completely uninstall phy from the terminal? Is there a specific command we can use?

**Comment by zuhayousuf** [comment]
When I tried to use 'conda uninstall phy2', this is what I got (Image attached). Does this seem like phy has been uninstalled successfully? And now I can reinstall phy2?
![uninstallphy](https://user-images.githubusercontent.com/56175933/80662918-2a521900-8a58-11ea-9133-f552f995e278.png)

**Comment by zuhayousuf** [comment]
I completely uninstalled phy and reinstalled using the instructions provided, but it's giving me an OSError again

**Comment by zuhayousuf** [comment]
Okay so after I reinstalled Anaconda, it seems to work. Thanks!

**Comment by TRuikes** [comment]
Had the same problem; even after a clean install according to instructions. It might be because phylib is installed through [pipy](https://pypi.org/project/phylib/) and that one is outdated?

**Comment by afonanar** [comment]
I am having a similar issue but with ´selector´ and not ´spikeselector´ and trying to follow the posted suggestions did not solved the problem. 
Also everything was working fine before, but some how it is not working anymore. 
If anyone has a suggestion I would appreciate a lot...

**Comment by afonanar** [comment]
> I had a similar issue after updating to the latest beta version of phy2. It seems that phylib was not updated in the process. I was abple to fix it by updating phylib through PyPI. On the phy2 environment I ran:
> `python3 -m pip install --upgrade phylib`

Thank you. It is working now
