### ISSUE TITLE
Phy TemplateGUI doesn't launch properly (blank window)

### ISSUE THREAD

**Issue by RenskeW** [cortex-lab/phy#1002]
Hi everyone,

A few days ago Phy2 stopped functioning properly on my computer. Whenever I try to launch it in Anaconda terminal the TemplateGUI window does appear but it stays completely blank, although I still can select clusters (they are just not visible). Using the --debug option didn't show any errors. Does anyone know what could be causing this problem? I am using Windows 10 and accessing my computer via Teamviewer (which didn't give problems in the past). 

Thanks! 

<img width="1158" alt="Schermafbeelding 2020-05-01 om 14 15 04" src="https://user-images.githubusercontent.com/64646852/80811197-af0e7580-8bc5-11ea-93fe-e1bdbd359a8d.png">
<img width="979" alt="Schermafbeelding 2020-05-01 om 14 19 59" src="https://user-images.githubusercontent.com/64646852/80811291-e0874100-8bc5-11ea-974d-3ceee697aeb0.png">
<img width="891" alt="Schermafbeelding 2020-05-01 om 14 20 57" src="https://user-images.githubusercontent.com/64646852/80811294-e3823180-8bc5-11ea-8dac-d3d38dd22771.png">

**Comment by RenskeW** [comment]
Could anybody please answer my question?

**Comment by JuliaT311** [comment]
Did you find a solution because I have the same problem

**Comment by RenskeW** [comment]
Sorry @JuliaT311, I forgot what happened in the end...

**Comment by malinroe** [comment]
@JuliaT311 I had the same problem when I worked remotely, and it was fixed after we updated some drivers (I can't remember which ones though, but maybe that can help you).
