### ISSUE TITLE
WaveformView not showing enough waveforms

### ISSUE THREAD

**Issue by yagui** [cortex-lab/phy#1003]
After doing some splits, sometimes I get a cluster showing no waveforms in the waveformView.
Here I have an example. Although this clusters are just noise, they represent what I'm saying.
![waveFormView](https://user-images.githubusercontent.com/4296015/80855295-16501800-8c0e-11ea-91a4-cdeace0f3f30.png)
Also for others cluster (like the one in red) that have more than 1000 waveforms, the waveformView shows around 20-30 waveforms.
I have the option cheange_n_spikes_waveforms at 2000, but I think it is only working as a ceil but the view shows only a small percentage of the amount of the cluster.

**Comment by rossant** [comment]
Hopefully this should now be fixed on the master branch of **phylib**, please reopen if not
