### ISSUE TITLE
Why is spike_times.npy a 2D NumPy array?

### ISSUE THREAD

**Issue by JoseGuzman** [cortex-lab/phy#1006]
[Question] After doing the spike curation with Phy2, I noticed that **spike_times.npy** is now a two-dimensional NumPy array.  I was wondering if this makes some sense, since this array will simply contain all spike times of all events. **spike_clusters.npy** is still a one-dimensional array.

**Comment by rossant** [comment]
spike_times is not supposed to be modified by phy2, unless there is an unexpected bug. What spike sorting software do you use? Can you double check that spike_times.npy is really modified by phy2 and not by another program?

**Comment by JoseGuzman** [comment]
I'm using KiloSort2 for sorting, it's probably a matlab-indexing issue.
