### ISSUE TITLE
could not create some views

### ISSUE THREAD

**Issue by annclem** [cortex-lab/phy#1038]
Hello, I just installed kilosort 2 and phy2 and it all seems to be working on my data however phy fails to open TraceView or TraceImageView. Might this be an installation problem? Thx!

**Comment by annclem** [comment]
i solved my own problem! continuous.dat must be in the output file from kilosort, wonderful.

**Comment by happyqiu** [comment]
Hi, I had the same issue with you, couldn't create traceview or traceimageview. But I didn't see continuous.dat, either. Could you tell me where this file is located? Thanks!
