### ISSUE TITLE
Selection of spikes in Waveform View

### ISSUE THREAD

**Issue by sv-bio** [cortex-lab/phy#1054]
Dear Cyrille,
Thank you for such a useful visualization tool. A short question regarding waveform view, that I could not find answer for in the forum: often I find that clusters have waveforms that were apparently mis-classified and are clearly different from the rest (peaks at different time, double peaks etc.; see figure as an example). How could I select these waveforms and move to a "garbage/noise cluster"?

![image](https://user-images.githubusercontent.com/58944642/99789461-4b30a780-2b2b-11eb-8717-d4f4654e337f.png)

System configuration:
Debian 10
Spyking Circus 0.9.9
PhyTemplate GUI 2.0b2.dev
phylib: v.2.3a0

Thanks,
Stan

**Comment by rossant** [comment]
Unfortunately selection in the waveform view is not possible at the moment

**Comment by sv-bio** [comment]
Thanks for the answer. Just as a side note, I found IMO handy implementation of this functionality in wave_clus Matlab toolbox.
