### ISSUE TITLE
Displaying messages from Logger in --debug mode

### ISSUE THREAD

**Issue by rhayman** [cortex-lab/phy#1114]
I've written a plugin for phy which works but would like to add some debug information which would display when phy is called in debug mode. I've copied what's been done in other places in the code base and tried:

```python
import logging
logger = logging.getLogger(__name__)

class MyPlugin(ManualClusteringView):
   def __init__(self, features=None):
        # blah
        logger.debug("Debug msg")
```

But no messages appear when I call phy like so:

```
phy template-gui params.py --debug
```

Am I missing something obvious?

**Comment by rossant** [comment]
I wonder if using:

```
logger = logging.getLogger("phy")
```

at line 2 would work?

Another possible solution might be to add a custom logging handler for your plugin.

**Comment by rhayman** [comment]
Happy to confirm that adding

```python
logger = logging.getLogger("phy")
```

worked a charm 

Thanks for the quick response
