### ISSUE TITLE
No AmplitudeView is displayed

### ISSUE THREAD

**Issue by EstherXSD** [cortex-lab/phy#1119]
Hi all, I'm wondering why there is nothing in my AmplitudeView of my phy.
![image](https://user-images.githubusercontent.com/66427267/137000527-ee3396e8-8a00-45f1-8e7d-e6a689c52e5e.png)
I'm running on M1 macbook (macOS Big Sur 11.6).

Many thanks!

**Comment by MarkDTu** [comment]
Hi EstherXSD

Currently deciding whether to move across to M1, but trying to gauge how it will affect workflow.

I guess you are spiking sorting on a different computer with Nvidia GPU then self curating etc onto MacBook?

Best
