### ISSUE TITLE
Windows didn't install Phy environment

### ISSUE THREAD

**Issue by crewl2** [cortex-lab/phy#1121]
I'm not sure were I went wrong here but I tried to install Phy, which I've done before, and it isn't installing. Unfortunately, I closed down the command prompt so I don't have the error.

**Comment by crewl2** [comment]
![image](https://user-images.githubusercontent.com/53056701/137998407-c1c8580d-f3b5-442a-b423-84bb191a6752.png)

I've also ran into these errors. I'm not sure where I went wrong.

**Comment by antimo-buonocore** [comment]
Hi, any update on this?

I tried a couple of things and if you manually create a new environment in anaconda and then install phy it works. I think in the previous version of the instructions they were explicitly specifying this step but now they removed anything related to anacoda and the command to create the new environment (you can check the history of the readme file).

So, for some reason, if you try to install phy on the base environment you would get conflicts.

Hope it makes sense (and that it's correct this way!).

**Comment by crewl2** [comment]
I tried that, but when I try to install phy again it just says requirements already satisfied. Is it too late? Should I reinstall windows?

**Comment by antimo-buonocore** [comment]
I don't think you need to reinstall windows. Uninstall phy with with pip uninstall, then delete the environment so that you can start from scratch. Create a new environment in anaconda, install pip, install phy. This should work.

**Comment by crewl2** [comment]
Okay, so I uninstall phy. Then I create the phy environment, then do I activate environment and install pip and phy in the activated environment??

**Comment by antimo-buonocore** [comment]
This worked for me. I believe you need a fresh environment (different from anaconda "base" environment ) to install phy. Before you were installing phy in anaconda "base" environment and this was not working.

**Comment by crewl2** [comment]
It worked. I uninstalled phy, created a phy environment, then installed pip and phy in the activated phy environment. Installing pip was a challenge for me because python commands were not installed in the environment, but I used the anaconda navigator to install everything in the phy environment. 

Thanks so much for the help. It worked!

**Comment by antimo-buonocore** [comment]
Great that it worked!

If I'm not wrong, you can install pip just with "conda install pip".

**Comment by antimo-buonocore** [comment]
To be precise, when you do "conda install pip" it will also install other packages needed by pip and python is one of them. So maybe to be precise, one should first create a new environment specifying the python version and then install pip and phy.

**Comment by eliezyer** [comment]
I was having the exact same problem, using xubuntu 18.04, and didn't understand why I couldn't install phy anymore. It would be good for a update on the installation instructions
