### ISSUE TITLE
phy 2.0 beta5 issue on Linux RedHat 8.1

### ISSUE THREAD

**Issue by Rummell** [cortex-lab/phy#1123]
When running with the lastest Anaconda 3 and Linux RedHat 8.1, on a fresh phy environment install, I have a problem trying to launch the GUI.

Following advice from Issue #875 unfortunately did **not** work.
i.e. Installing pyqt from anaconda instead of pip ( conda install -c anaconda pyqt)

The error msg I got after running export QT_DEBUG_PLUGINS=1 beforehand was this:

Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/mnt/pns/home/anaconda3/envs/phy2b5/bin/platforms" ...
Cannot load library /mnt/pns/home/anaconda3/envs/phy2b5/lib/python3.7/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so: (libxcb-icccm.so.4: cannot open shared object file: No such file or directory)
QLibraryPrivate::loadPlugin failed on "/mnt/pns/home/anaconda3/envs/phy2b5/lib/python3.7/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so" : "Cannot load library /mnt/pns/home/anaconda3/envs/phy2b5/lib/python3.7/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so: (libxcb-icccm.so.4: cannot open shared object file: No such file or directory)"
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Any help would be greatly appreciated..

**Comment by mwawra** [comment]
Hello @Rummell , I'm quite late, but did you solved the problem. Currently I'm trying to run Phy on Kubuntu 21.10 and saw the same problems. But only in Wayland-Sessions. When I switch to X11 phy works normally. In RedHat Linux 8 the default display server is also Wayland, what might explain your problems.

Does anybody successfully managed to run Phy in a Wayland session?
