### ISSUE TITLE
Blank ClusterView and SimilarityView

### ISSUE THREAD

**Issue by AntonioST** [cortex-lab/phy#1143]
Hi,

I got some problem to start with a template-gui on my kilosort result. The ClusterView and SimilarityView didn't show anything. No mater how long I wait, it didn't change the blank content. If I tried to close the window, a timeout dialog pop up.

![Screenshot_2022-03-11_19-43-55](https://user-images.githubusercontent.com/6375955/157932171-15386bec-4512-414a-906a-c913568be363.png)

Here are the part of packages installed in my conda environment.

```
# Name                    Version                   Build  Channel
pyqt5                     5.15.5                   pypi_0    pypi
pyqt5-qt                  5.15.2                   pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.9.1                   pypi_0    pypi
pyqtwebengine             5.15.5                   pypi_0    pypi
pyqtwebengine-qt          5.15.2                   pypi_0    pypi
pyqtwebengine-qt5         5.15.2                   pypi_0    pypi
pytest-qt                 3.2.2                    pypi_0    pypi
qtconsole                 4.5.5                    pypi_0    pypi
phy                       2.0a1                    pypi_0    pypi
phylib                    2.4.1                    pypi_0    pypi
```

I guess it is something relate to the QtWebEngine which js wasn't run.

Thanks

**Comment by AliyaAbl** [comment]
I have the same problem. Have you found a solution to this?

**Comment by AntonioST** [comment]
Hi @AliyaAbl 

I don't the real reason why qtwebengine is unable to show html content, but this command works on my linux compute 
`env QTWEBENGINE_CHROMIUM_FLAGS="--single-process" phy template-gui .../params.py`.


![Screenshot_2022-03-18_14-29-46](https://user-images.githubusercontent.com/6375955/159012009-31662a57-f72e-4002-a3bb-33c45cce2c5d.png)

 I just find out this way this morning. I tried a simple QWebEngineView example with conda Qt (pyqtwebengine-qt 5.15.2 from conda pypi chanel), and my OS Qt (python-pyqt5-webengine-5.15.5-4 from archlinux). I have no such issue with my OS Qt.

**Comment by abhijithkrishnan93** [comment]
I have the same problem and this  @AntonioST solution works.

**Comment by arthurz323** [comment]
had the same issue, and solution from @AntonioST works for me too, thanks!

**Comment by alejoe91** [comment]
> Hi @AliyaAbl
> 
> I don't the real reason why qtwebengine is unable to show html content, but this command works on my linux computer `env QTWEBENGINE_CHROMIUM_FLAGS="--single-process" phy template-gui .../params.py`.
> 
> ![Screenshot_2022-03-18_14-29-46](https://user-images.githubusercontent.com/6375955/159012009-31662a57-f72e-4002-a3bb-33c45cce2c5d.png)
> 
> I just find out this way this morning. I tried a simple QWebEngineView example with conda Qt (pyqtwebengine-qt 5.15.2 from conda pypi chanel), and my OS Qt (python-pyqt5-webengine-5.15.5-4 from archlinux). I have no such issue with my OS Qt.

@rossant could you add this to the Troubleshoot section?

**Comment by KBillel** [comment]
Worked for me as well thank you !

**Comment by Datamance** [comment]
@AntonioST You are a lifesaver! Thank you.

**Comment by Coglet00** [comment]
hey i am a bit inexperienced but where should i write the env QTWEBENGINE_CHROMIUM_FLAGS="--single-process" phy template-gui .../params.py. command exactly?

**Comment by rory-bedford** [comment]
Hey @Coglet00, I'm guessing you're on linux?

In bash, you can define an environment variable for the execution of a specific command by putting it before the command. So in this case, we're setting QTWEBENGINE_CHROMIUM_FLAGS to "--single-process", then just running the usual command 'phy template-gui params.py'. The env bit at the start shouldn't matter much (it just runs the command in a clean environment). So in your terminal, navigate to the phy data directory, make sure it has params.py in your current directory, then run the command (don't actually put the .../ at the start).

**Comment by rory-bedford** [comment]
Just to clarify is that on the same line? So your full command should be:

```
QTWEBENGINE_CHROMIUM_FLAGS="--single-process" phy template-gui params.py
```

If you run them on different lines the environment variable QTWEBENGINE_CHROMIUM_FLAGS won't get saved for when you run the next command.

Sorry if this is pedantic just checking though!

**Comment by RuchaBJoshi** [comment]
I am experiencing the same issue as #1143
How do I resolve this on Windows 11? I think the solution on here is to do with Linux PCs.

**Comment by rossant** [comment]
Can you try the release candidate? https://phy.readthedocs.io/en/latest/release/#phy-210rc1
