### ISSUE TITLE
Phy won't open TemplateFeatureView

### ISSUE THREAD

**Issue by diogoflduarte** [cortex-lab/phy#1145]
Hi everyone,

I'm getting the following error:
`16:45:46.127 [W] gui:671              Could not create view TemplateFeatureView.`
whenever I try to open the TemplateFeatureView on a fresh install of Phy under windows, working on a dataset sorted with Kilosort3.

Here's what I tried: 

adding the `--debug` tag did not output any message related to this.

adding `--clear-cache` and `--clear-state` did not make a difference, so I'm convinced it's not a corrupted configuration.

Without the TemplateFeatureView, merging and splitting operations are compromised... anyone else having this issue, or even better, a fix?

EDIT: same applies to `FeatureView`

**Comment by diogoflduarte** [comment]
UPDATE 1: phy dev has the same behavior on KS3 datasets.

UPDATE 2: I re-sorted the same dataset using Kilosort2.5 and I now have the TemplateFeatureView, and better even, the FeatureView.

Any guess on what causes this?

**Comment by GrimmSnark** [comment]
Hello,

I think TemplateFeature view has been phased out of kilosort3. 

Feature view can be reenabled by separately running 

`phy extract-waveforms params.py`

through your phy python command line.

Good luck,

Michael

**Comment by diogoflduarte** [comment]
Tested and confirmed this works!

Thank you!!
