### ISSUE TITLE
cluster view and similarity view not shown

### ISSUE THREAD

**Issue by sbyoo** [cortex-lab/phy#1151]
Hello

I am trying to use phy in the Mac mini with Big Sur as OS. I installed identical dependencies to the current Mac in another Mac, in which phy runs perfectly. However, in this Mac, all other function works except the cluster view and similarity view (screenshot attached). Your help will be greatly appreciated. Thank you.

Best,
![phy_issue](https://user-images.githubusercontent.com/23562583/162602345-b00979a8-5218-4cc9-a3b8-f9c9770d8d8b.png)

**Comment by Mousakr** [comment]
Hi,

I unfortunately have the same issue. I use fedora linux version 35, with a newly installed python environment (same issue arises for python 3.7 , 3.8 and 3.10) and newly installed phy. When I attempt to close the GUI, I get the following error (I am unsure if it is related...):

17:53:42.598 [E] qt:178               Timeout in _block().

**Comment by kissadamfkut** [comment]
Same issue here. It's been happening since the last OS upgrade (Manjaro). The following packages have been upgraded when it turned broken:

[packages.txt](https://github.com/cortex-lab/phy/files/8651164/packages.txt)

**Comment by arthurz323** [comment]
same issue! running on os fedora 36, kernel 5.17.8.

**Comment by brandonStell** [comment]
This response https://github.com/cortex-lab/phy/issues/1143#issuecomment-1072420729 solved the problem for me on Ubuntu 22.04.
