### ISSUE TITLE
ClusterView problem

### ISSUE THREAD

**Issue by churanj** [cortex-lab/phy#1156]
Hello,
we have a similar problem like issue #1151 but with some interesting differences. We use a neuropixels probe and kilosort3. When we run phy on the output of kilosort , the ClusterView window remains blank, however, the SimilarityView window seems intact (see screenshot). Importantly, this issue only occurs in a part (~50%) of our recordings while other work nicely. When it occurs, it is independent of the machine we run phy at - currently we tested it at two Windows11 and two MacOS systems. When I compare the Kilosort outputs between the ‘working’ and ’not working’ measurements I also don’t see any obvious major differences. So far the mystery… Any suggestions or speculations?
Best!
Jan 
![Screen Shot 2022-05-11 at 16 02 16 (2)](https://user-images.githubusercontent.com/86953185/167894750-8b6af2be-93da-4de6-b4ab-e44fbd729865.png)

**Comment by churanj** [comment]
An update on this issue: Apparently the cause of the problem is a file named 'metrics.csv' that is generated in the post-processing stages on the neuropixels processing pipeline. When we delete this file from the kilosort results directory, everything seems to work work fine. The content of the file looks like a table of the clusters and their properties. We are, however, not sure, what this file was supposed to do for phy and whether it is save to delete it. It would be great to get some insight into the functions of that file.
Best!
Jan

**Comment by arthurz323** [comment]
Hello,

I have encountered the same issue. However, i do not have such `metrics.cvs` file in my output folder. Opened two sorted sessions, and they had the same problem.
Here is the screenshot of the error message:
![Screenshot from 2022-05-20 18-58-09](https://user-images.githubusercontent.com/77285087/169587738-6dc229e7-ca6a-4058-9964-ca8aa80f52d5.png)

Best,
Arthur
