### ISSUE TITLE
spyder 5.1.5 requires pyqt5<5.13

### ISSUE THREAD

**Issue by mariehemelt** [cortex-lab/phy#1160]
I've been using phy for a while but we recently had to rebuild our server and I am re-installing everything. When I run 
pip install phy --pre --upgrade 
I eventually get the following error: 
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spyder 5.1.5 requires pyqt5<5.13, but you have pyqt5 5.15.6 which is incompatible.
spyder 5.1.5 requires pyqtwebengine<5.13, but you have pyqtwebengine 5.15.5 which is incompatible.
My understanding of python is pretty limited, can you offer any basic advice for dealing with this- installing pyqt5 & pyqtwebengine < 5.13, it seems?
Thanks.

**Comment by GrimmSnark** [comment]
There are two options you can try. First is to downgrade the packages in question using:

```
pip install --upgrade --user pyqtwebengine==5.12
pip install --upgrade --user pyqt5==5.12
```

Or you can install everything in a conda environment. This is what I do and I am able to run everything without any dependency issues. 
In anaconda command window:

1. Creating conda environment: `conda create --name`
2. Activate conda enviroment: ` conda activate name`
3. Install everything as normal 
4. NB to run Phy you will need to activate the environment every time. 

If you have any more questions, feel free to ask me.

Michael

**Comment by saratorabi-github** [comment]
I am installing keras and tensor flow but when I start working with spyder i get the bellow error, I would be grateful that any body could help me with that:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spyder 5.2.2 requires pyqt5<5.13, which is not installed.
spyder 5.2.2 requires pyqtwebengine<5.13, which is not installed.
daal4py 2021.6.0 requires daal==2021.4.0, which is not installed.
anaconda-project 0.11.1 requires ruamel-yaml, which is not installed.
numba 0.55.1 requires numpy<1.22,>=1.18, but you have numpy 1.24.1 which is incompatible.
conda-repo-cli 1.0.20 requires clyent==1.2.1, but you have clyent 1.2.2 which is incompatible.
conda-repo-cli 1.0.20 requires nbformat==5.4.0, but you have nbformat 5.5.0 which is incompatible.
conda-repo-cli 1.0.20 requires requests==2.28.1, but you have requests 2.28.2 which is incompatible.

**Comment by number1010** [comment]
> 

Did you fix that error? Can you tell me how to fix it? Thanks

**Comment by number1010** [comment]
> I am installing keras and tensor flow but when I start working with spyder i get the bellow error, I would be grateful that any body could help me with that: ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. spyder 5.2.2 requires pyqt5<5.13, which is not installed. spyder 5.2.2 requires pyqtwebengine<5.13, which is not installed. daal4py 2021.6.0 requires daal==2021.4.0, which is not installed. anaconda-project 0.11.1 requires ruamel-yaml, which is not installed. numba 0.55.1 requires numpy<1.22,>=1.18, but you have numpy 1.24.1 which is incompatible. conda-repo-cli 1.0.20 requires clyent==1.2.1, but you have clyent 1.2.2 which is incompatible. conda-repo-cli 1.0.20 requires nbformat==5.4.0, but you have nbformat 5.5.0 which is incompatible. conda-repo-cli 1.0.20 requires requests==2.28.1, but you have requests 2.28.2 which is incompatible.

Did you fix that error? Can you tell me how to fix it? Thanks

**Comment by charbossly** [comment]
Try this pip install --upgrade --user pyqt5==5.12

**Comment by tanayapanhale** [comment]
I tried first method but i get the following error now:
PS C:\Tanaya Coding Projects\ML Projects\movies-recommender-system> pip install --upgrade --user pyqtwebengine==5.12      
ERROR: Could not find a version that satisfies the requirement pyqtwebengine==5.12 (from versions: 5.12.1, 5.14.0, 5.15.0, 5.15.1, 5.15.2, 5.15.3, 5.15.4, 5.15.5, 5.15.6)
ERROR: No matching distribution found for pyqtwebengine==5.12
PS C:\Tanaya Coding Projects\ML Projects\movies-recommender-system> pip install --upgrade --user pyqt5==5.12
ERROR: Could not find a version that satisfies the requirement pyqt5==5.12 (from versions: 5.12.3, 5.14.0, 5.14.1, 5.14.2, 5.15.0, 5.15.1, 5.15.2, 5.15.3, 5.15.4, 5.15.5, 5.15.6, 5.15.7, 5.15.8, 5.15.9)
ERROR: No matching distribution found for pyqt5==5.12

What to do to resolve it?

**Comment by lynetteyuepan** [comment]
> I tried first method but i get the following error now: PS C:\Tanaya Coding Projects\ML Projects\movies-recommender-system> pip install --upgrade --user pyqtwebengine==5.12 ERROR: Could not find a version that satisfies the requirement pyqtwebengine==5.12 (from versions: 5.12.1, 5.14.0, 5.15.0, 5.15.1, 5.15.2, 5.15.3, 5.15.4, 5.15.5, 5.15.6) ERROR: No matching distribution found for pyqtwebengine==5.12 PS C:\Tanaya Coding Projects\ML Projects\movies-recommender-system> pip install --upgrade --user pyqt5==5.12 ERROR: Could not find a version that satisfies the requirement pyqt5==5.12 (from versions: 5.12.3, 5.14.0, 5.14.1, 5.14.2, 5.15.0, 5.15.1, 5.15.2, 5.15.3, 5.15.4, 5.15.5, 5.15.6, 5.15.7, 5.15.8, 5.15.9) ERROR: No matching distribution found for pyqt5==5.12
> 
> What to do to resolve it?

Below should work:
```
pip install --upgrade --user pyqtwebengine==5.12.1
pip install --upgrade --user pyqt5==5.12.3

```

**Comment by zm711** [comment]
I will close this since it seems settled.
