### ISSUE TITLE
Claculating Isolation Distance and Likelihood Ratio

### ISSUE THREAD

**Issue by AJPerez-Ignacio** [cortex-lab/phy#1161]
Hello,

I want to create a plugin that calculates the isolation distance (IsoD) and likelihood ratio (Lratio) of a cluster. I know how to calculate these values for features on a single channel, but I am unsure of how to calculate this when there is multiple channels as my feature. How would I go about calculating this when there is multiple channels as my feature? Do you recommend picking the best channel (channel with the largest feature), or is there some other calculation on how to do this?

How to calculate IsoD and Lratio: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4200702/

Thanks.

**Comment by zm711** [comment]
https://github.com/cortex-lab/sortingQuality
Nick Steinmetz has done a version in matlab if you want to check that out here. You can always adapt this for your purposes.

**Comment by zm711** [comment]
I'll close. Feel free to open a new issue if something else comes up.
