### ISSUE TITLE
Help with understanding ISIview and finding the number of spikes in each bin

### ISSUE THREAD

**Issue by ryoiwata** [cortex-lab/phy#1215]
Hey all!

Quick question with the ISI view. What are the numbers on the Y-axis in the ISI view?

We are trying to find a way to count the number of spikes that occurred within the two center bins/bars for refractory period violations. Currently, we are counting the smallest difference between adjacent bins as one spike. And then counting the number of spikes in other bins based on how many multiples of the smallest difference in terms of height that the bin's height is. Please let us know if there's a simpler way to find the number of spikes in the different bins. Thank you so much for any help!

![image](https://github.com/cortex-lab/phy/assets/42358679/7cae4707-b084-4f01-ab5f-e16c3cafcbd7)

**Comment by zm711** [comment]
@ryoiwata 

It would be pretty easy to do that outside of `Phy`.  You just load in `spike_times.npy` and `spike_clusters.npy`. Then to get the ISI you just do something like:

```python
spike_clusters = np.squeeze(np.load('spike_clusters.npy'))
spike_times = np.squeeze(np.load('spike_times.npy')) # these are raw will need sample rate later
for cluster in np.unique(spike_clusters):
    current_spike_times = spike_times[spike_clusters==cluster]
    total_spikes = len(current_spike_times)
    current_isi = np.diff(current_spike_times) * sample_rate # this is stored in the params.py file
    number_violations= len(current_isi[current_isi>refractory_period]) # you put in whatever refractory period you want as written in seconds

```

Then you save the `number_violations` for each cluster and `total_spikes` for each cluster.

There are some more sophisticated approaches. You can check out [spikeinterface](https://spikeinterface.readthedocs.io/en/latest/modules/qualitymetrics/isi_violations.html) which can load `Phy` directories and do some of the math for you or you could read up on the different types of more statistical-like tests for doing refractory period violations.

Or you could check out [sortingQuality](https://github.com/cortex-lab/sortingQuality) if you prefer Matlab.
