### ISSUE TITLE
ISI in logspace rather than linear

### ISSUE THREAD

**Issue by adredish** [cortex-lab/phy#1216]
I would like to have the ISI histogram be of log(ISI) rather than a linear ISI.  This is much better to see ISI shapes, as the real issues appear at oscillatory frequencies in log space.  (EMG noise, for example, has a very specific shape in log ISI space.)  

What is the easiest way to implement this?  I assume that there is a simple function doing the ISI calculation and displaying it.  Where are those calculations done?

thanks

**Comment by zm711** [comment]
https://github.com/cortex-lab/phy/blob/master/phy/cluster/views/histogram.py

The histogram based functions (including ISI) are performed there. 

https://phy.readthedocs.io/en/latest/plugins/

How to make your own personal plug-in to use with phy included in the documentation above.

Cheers,
Zach
