### ISSUE TITLE
"zsh: segmentation fault  phy template-gui params.py"

### ISSUE THREAD

**Issue by syedtamim4nov** [cortex-lab/phy#1244]
The following error occurs when I run the line ' phy template-gui params.py' in terminal. I am an undergraduate trying to learn and master Phy and any help would be highly appreciated.

**Comment by zm711** [comment]
@syedtamim4nov

zsh is the base shell for Macs. Since Phy relies heavily on openGL, it isn't super friendly with Macs any more.

Could you let us know your OS and copy the contents of a:

```python
conda list
```
inside your environment (if you're using conda--if using a python virtual env then the equivalent.

**Comment by syedtamim4nov** [comment]
The MacOS is Sonoma 14.1

# packages in environment at /Users/syedtamimahmad/anaconda3/envs/phy2:
#
# Name                    Version                   Build  Channel
abseil-cpp                20230802.0           h313beb8_2  
appnope                   0.1.2           py311hca03da5_1001  
arrow-cpp                 11.0.0               hc7aafb3_2  
asttokens                 2.0.5              pyhd3eb1b0_0  
aws-c-common              0.6.8                h80987f9_1  
aws-c-event-stream        0.1.6                h313beb8_6  
aws-checksums             0.1.11               h80987f9_2  
aws-sdk-cpp               1.8.185              ha71a6ea_1  
backcall                  0.2.0              pyhd3eb1b0_0  
blas                      1.0                    openblas  
bokeh                     3.3.0           py311hb6e6a13_0  
boost-cpp                 1.82.0               h48ca7d4_2  
bottleneck                1.3.5           py311ha0d4635_0  
brotli                    1.0.9                h1a28f6b_7  
brotli-bin                1.0.9                h1a28f6b_7  
brotli-python             1.0.9           py311h313beb8_7  
bzip2                     1.0.8                h620ffc9_4  
c-ares                    1.19.1               h80987f9_0  
ca-certificates           2023.12.12           hca03da5_0  
certifi                   2023.11.17      py311hca03da5_0  
cffi                      1.16.0          py311h80987f9_0  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.1.7           py311hca03da5_0  
cloudpickle               2.2.1           py311hca03da5_0  
colorcet                  3.0.1                    pypi_0    pypi
comm                      0.1.2           py311hca03da5_0  
contourpy                 1.2.0           py311h48ca7d4_0  
cryptography              41.0.7          py311hd4332d6_0  
cycler                    0.11.0             pyhd3eb1b0_0  
cyrus-sasl                2.1.28               h9131b1a_1  
cython                    3.0.6           py311h80987f9_0  
cytoolz                   0.12.2          py311h80987f9_0  
dask                      2023.11.0       py311hca03da5_0  
dask-core                 2023.11.0       py311hca03da5_0  
debugpy                   1.6.7           py311h313beb8_0  
decorator                 5.1.1              pyhd3eb1b0_0  
distributed               2023.11.0       py311hca03da5_0  
executing                 0.8.3              pyhd3eb1b0_0  
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.12.1               h1192e45_0  
fsspec                    2023.10.0       py311hca03da5_0  
gettext                   0.21.0               h13f89a0_1  
gflags                    2.2.2                hc377ac9_0  
ghp-import                2.1.0                    pypi_0    pypi
giflib                    5.2.1                h80987f9_3  
glib                      2.69.1               h514c7bf_2  
glog                      0.5.0                hc377ac9_0  
grpc-cpp                  1.48.2               hc60591f_4  
gst-plugins-base          1.14.1               h313beb8_1  
gstreamer                 1.14.1               h80987f9_1  
gtest                     1.14.0               h48ca7d4_0  
h5py                      3.9.0           py311hba6ad2f_0  
hdf5                      1.12.1               h05c076b_3  
heapdict                  1.0.1              pyhd3eb1b0_0  
icu                       73.1                 h313beb8_0  
idna                      3.4             py311hca03da5_0  
importlib-metadata        6.0.0           py311hca03da5_0  
iniconfig                 1.1.1              pyhd3eb1b0_0  
ipykernel                 6.25.0          py311hb6e6a13_0  
ipython                   8.15.0          py311hca03da5_0  
jedi                      0.18.1          py311hca03da5_1  
jinja2                    3.1.2           py311hca03da5_0  
joblib                    1.2.0           py311hca03da5_0  
jpeg                      9e                   h80987f9_1  
jupyter_client            8.6.0           py311hca03da5_0  
jupyter_core              5.5.0           py311hca03da5_0  
kiwisolver                1.4.4           py311h313beb8_0  
klusta                    3.0.16                   pypi_0    pypi
klustakwik2               0.2.6                    pypi_0    pypi
krb5                      1.20.1               hf3e1bf2_1  
lcms2                     2.12                 hba8e193_0  
lerc                      3.0                  hc377ac9_0  
libboost                  1.82.0               h0bc93f9_2  
libbrotlicommon           1.0.9                h1a28f6b_7  
libbrotlidec              1.0.9                h1a28f6b_7  
libbrotlienc              1.0.9                h1a28f6b_7  
libclang                  14.0.6          default_h1b80db6_1  
libclang13                14.0.6          default_h24352ff_1  
libcurl                   8.4.0                h3e2b118_1  
libcxx                    14.0.6               h848a8c0_0  
libdeflate                1.17                 h80987f9_1  
libedit                   3.1.20230828         h80987f9_0  
libev                     4.33                 h1a28f6b_1  
libevent                  2.1.12               h02f6b3c_1  
libffi                    3.4.4                hca03da5_0  
libgfortran               5.0.0           11_3_0_hca03da5_28  
libgfortran5              11.3.0              h009349e_28  
libiconv                  1.16                 h1a28f6b_2  
libllvm14                 14.0.6               h7ec7a93_3  
libnghttp2                1.57.0               h62f6fdd_0  
libopenblas               0.3.21               h269037a_0  
libpng                    1.6.39               h80987f9_0  
libpq                     12.15                h02f6b3c_1  
libprotobuf               3.20.3               h514c7bf_0  
libsodium                 1.0.18               h1a28f6b_0  
libssh2                   1.10.0               h02f6b3c_2  
libthrift                 0.15.0               h73c2103_2  
libtiff                   4.5.1                h313beb8_0  
libwebp                   1.3.2                ha3663a8_0  
libwebp-base              1.3.2                h80987f9_0  
libxml2                   2.10.4               h0dcf63f_1  
llvm-openmp               14.0.6               hc6e5704_0  
locket                    1.0.0           py311hca03da5_0  
lz4                       4.3.2           py311h80987f9_0  
lz4-c                     1.9.4                h313beb8_0  
markdown                  3.5.1                    pypi_0    pypi
markupsafe                2.1.1           py311h80987f9_0  
matplotlib                3.8.0           py311hca03da5_0  
matplotlib-base           3.8.0           py311h7aedaa7_0  
matplotlib-inline         0.1.6           py311hca03da5_0  
mergedeep                 1.3.4                    pypi_0    pypi
mkdocs                    1.5.3                    pypi_0    pypi
msgpack-python            1.0.3           py311h48ca7d4_0  
mtscomp                   1.0.2                    pypi_0    pypi
munkres                   1.1.4                      py_0  
mysql                     5.7.24               ha71a6ea_2  
ncurses                   6.4                  h313beb8_0  
nest-asyncio              1.5.6           py311hca03da5_0  
numexpr                   2.8.7           py311h6dc990b_0  
numpy                     1.26.2          py311he598dae_0  
numpy-base                1.26.2          py311hfbfe69c_0  
openjpeg                  2.3.0                h7a6adac_2  
openssl                   3.0.12               h1a28f6b_0  
orc                       1.7.4                hdca1487_1  
packaging                 23.1            py311hca03da5_0  
pandas                    2.1.4           py311h7aedaa7_0  
param                     2.0.1                    pypi_0    pypi
parso                     0.8.3              pyhd3eb1b0_0  
partd                     1.4.1           py311hca03da5_0  
pathspec                  0.12.1                   pypi_0    pypi
pcre                      8.45                 hc377ac9_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
phy                       2.0b5                    pypi_0    pypi
phylib                    2.4.3                    pypi_0    pypi
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    10.0.1          py311h3b245a6_0  
pip                       23.3.1          py311hca03da5_0  
platformdirs              3.10.0          py311hca03da5_0  
pluggy                    1.0.0           py311hca03da5_1  
ply                       3.11            py311hca03da5_0  
prompt-toolkit            3.0.36          py311hca03da5_0  
psutil                    5.9.0           py311h80987f9_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pure_eval                 0.2.2              pyhd3eb1b0_0  
pyarrow                   11.0.0          py311h7575258_1  
pycparser                 2.21               pyhd3eb1b0_0  
pyct                      0.5.0                    pypi_0    pypi
pygments                  2.15.1          py311hca03da5_1  
pyopengl                  3.1.1a1         py311hca03da5_0  
pyopenssl                 23.2.0          py311hca03da5_0  
pyparsing                 3.0.9           py311hca03da5_0  
pyqt                      5.15.10         py311h313beb8_0  
pyqt5-sip                 12.13.0         py311h80987f9_0  
pyqtwebengine             5.15.10         py311h313beb8_0  
pysocks                   1.7.1           py311hca03da5_0  
pytest                    7.4.0           py311hca03da5_0  
python                    3.11.5               hb885b13_0  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-lmdb               1.4.1           py311h313beb8_0  
python-tzdata             2023.3             pyhd3eb1b0_0  
pytz                      2023.3.post1    py311hca03da5_0  
pyyaml                    6.0.1           py311h80987f9_0  
pyyaml-env-tag            0.1                      pypi_0    pypi
pyzmq                     25.1.0          py311h313beb8_0  
qt-main                   5.15.2              h0917680_10  
qt-webengine              5.15.9               h2903aaf_7  
qtconsole                 5.5.0           py311hca03da5_0  
qtpy                      2.4.1           py311hca03da5_0  
re2                       2022.04.01           hc377ac9_0  
readline                  8.2                  h1a28f6b_0  
requests                  2.31.0          py311hca03da5_0  
responses                 0.13.3             pyhd3eb1b0_0  
scikit-learn              1.2.2           py311h313beb8_1  
scipy                     1.11.4          py311hc76d9b0_0  
setuptools                68.2.2          py311hca03da5_0  
sip                       6.7.12          py311h313beb8_0  
six                       1.16.0             pyhd3eb1b0_1  
snappy                    1.1.10               h313beb8_1  
sortedcontainers          2.4.0              pyhd3eb1b0_0  
sqlite                    3.41.2               h80987f9_0  
stack_data                0.2.0              pyhd3eb1b0_0  
tblib                     1.7.0              pyhd3eb1b0_0  
threadpoolctl             2.2.0              pyh0d69192_0  
tk                        8.6.12               hb8d0fd4_0  
toolz                     0.12.0          py311hca03da5_0  
tornado                   6.3.3           py311h80987f9_0  
tqdm                      4.66.1                   pypi_0    pypi
traitlets                 5.7.1           py311hca03da5_0  
tzdata                    2023c                h04d1e81_0  
urllib3                   1.26.18         py311hca03da5_0  
utf8proc                  2.6.1                h1a28f6b_0  
watchdog                  3.0.0                    pypi_0    pypi
wcwidth                   0.2.5              pyhd3eb1b0_0  
wheel                     0.41.2          py311hca03da5_0  
xyzservices               2022.9.0        py311hca03da5_1  
xz                        5.4.5                h80987f9_0  
yaml                      0.2.5                h1a28f6b_0  
zeromq                    4.3.4                hc377ac9_0  
zict                      3.0.0           py311hca03da5_0  
zipp                      3.11.0          py311hca03da5_0  
zlib                      1.2.13               h5a0b063_0  
zstd                      1.5.5                hd90d995_0

**Comment by zm711** [comment]
So as I said unfortunately the current version of MacOS isn't really compatible with Phy any more and since phy isn't being actively developed at the moment it likely won't work. Your best bet is to use a Linux or Windows computer for this analysis.

**Comment by syedtamim4nov** [comment]
@zm711 

I am using VS Code on MacOs Sonoma 14.1....... is there any way to rectify the issue? Thanks a lot for the input!

**Comment by syedtamim4nov** [comment]
@zm711 Thanks a lot!

**Comment by zm711** [comment]
Of course. If you run into any install issue on a different computer just let me know--happy to help.
