### ISSUE TITLE
most recent python 3.12 removes imp 

### ISSUE THREAD

**Issue by ryan-budde** [cortex-lab/phy#1251]
The most recent python 3.12 standard conda environment no longer includes imp, which may cause multiple errors, but failed first for me at C:\Users\ryanb\anaconda3\envs\phy2\Lib\site-packages\phy\utils\plugin.py line 14.

appending the snippet `python=3.11` to the end of the conda initialization line fixes the issue. A temporary fix could be updating that line with 3.11 on the Readme, until imp is replaced.

**Comment by bainro** [comment]
Same issue, we had to downgrade to 3.9
