### ISSUE TITLE
AmplitudeView not showing raw due to error "model:667 Skipping spike waveforms"

### ISSUE THREAD

**Issue by K-Onod** [cortex-lab/phy#1264]
I set up phy2 on my new Windows 11. I successfully loaded up phy2 (phy TemplateGUI v2.0b5, phylib v2.4.3) using environment.yml ([#1218](https://github.com/cortex-lab/phy/issues/1218)). After launching phy template-gui params.py, I can open phy, but then encountered:

17:46:01.340 [W] model:603            Unreferenced clusters found in templates (generally not a problem)
17:46:01.640 [W] model:625            Unreferenced clusters found in spike_clusters (generally not a problem)
17:46:01.790 [W] model:667            Skipping spike waveforms that do not exist, they will be extracted on the fly from the raw data as needed.

I think that all phy operations would work, except for AmlitudeView not showing raw amplitude, which can be explained by model:667 sentence. I successfully ran phy using the same spike data on my old computer where phy2 was loaded more than three years ago (phy TemplateGUI v2.0a1, phylib v2.0a3). So, the error reason does not result from the data itself.

How can I fix it?

Thanks for your help!

--
PS. I attached the conda lists and "phy template-gui params.py --debug" outputs below.
[text1.txt](https://github.com/cortex-lab/phy/files/14833516/text1.txt)
[text2.txt](https://github.com/cortex-lab/phy/files/14833518/text2.txt)

**Comment by alirza67** [comment]
> I set up phy2 on my new Windows 11. I successfully loaded up phy2 (phy TemplateGUI v2.0b5, phylib v2.4.3) using environment.yml ([#1218](https://github.com/cortex-lab/phy/issues/1218)). After launching phy template-gui params.py, I can open phy, but then encountered:
> 
> 17:46:01.340 [W] model:603 Unreferenced clusters found in templates (generally not a problem) 17:46:01.640 [W] model:625 Unreferenced clusters found in spike_clusters (generally not a problem) 17:46:01.790 [W] model:667 Skipping spike waveforms that do not exist, they will be extracted on the fly from the raw data as needed.
> 
> I think that all phy operations would work, except for AmlitudeView not showing raw amplitude, which can be explained by model:667 sentence. I successfully ran phy using the same spike data on my old computer where phy2 was loaded more than three years ago (phy TemplateGUI v2.0a1, phylib v2.0a3). So, the error reason does not result from the data itself.
> 
> How can I fix it?
> 
> Thanks for your help!
> 
> -- PS. I attached the conda lists and "phy template-gui params.py --debug" outputs below. [text1.txt](https://github.com/cortex-lab/phy/files/14833516/text1.txt) [text2.txt](https://github.com/cortex-lab/phy/files/14833518/text2.txt)

Hi, 
I am having the same problem. I don't think the not having the amplitude is due to "model:667 Skipping spike waveforms" .
you can solve the "skipping spike waveform" by the following command:
 phy  extract-waveforms params.py

**Comment by K-Onod** [comment]
Thanks, alirza67! The "[W] model:667 Skipping spike waveforms" was gone after launching phy extract-waveforms params.py. I appreciate you.

Yet, it has no raw amplitude for AmplitudeView. That raw amplitude is very useful for removing sudden artifacts related to motion or LED illumination. So, I still need to fix it.

**Comment by zm711** [comment]
@K-Onod,

Which KS are you using? I agree amplitudes are super important :) based on your --debug it looks like Phy thinks it's loading amplitudes. So I think we need to start with what sorter you used and are there amplitude files in the directory?

**Comment by K-Onod** [comment]
Hi, zm711. Here is my dataset loaded in phy. Please let me know if you need actual files.
![dataset](https://github.com/cortex-lab/phy/assets/104319193/681ddaee-ce3c-4dd4-8ec3-fb907aeee3d1)

**Comment by zm711** [comment]
And which kilosort are you using?

**Comment by K-Onod** [comment]
I use kilosort 2.5.

**Comment by K-Onod** [comment]
That problem was fixed. See https://github.com/cortex-lab/phy/issues/1175.
