### ISSUE TITLE
Segmentation Fault when running phy

### ISSUE THREAD

**Issue by mattslab** [cortex-lab/phy#1271]
I get a Segmentation Fault when running phy. This is Ubuntu 22.04, with phy installed via anaconda. Had to force 3.11 install, which I did using this:

$ conda create --name phy_custom python=3.11
$ conda install cython dask h5py joblib matplotlib numpy pillow pyopengl pyqt pyqtwebengine pytest qtconsole requests responses scikit-learn scipy traitlets --freeze-installed

Then follow the rest of the readme instructions. Doing this got around the "imp" issue that I had at first, and phy runs. However, I get a seg fault. More info below on the debug output and the conda environment, but any ideas? Thanks!

(phy_custom) $ phy template-gui params.py
08:54:08.740 [W] model:667            Skipping spike waveforms that do not exist, they will be extracted on the fly from the raw data as needed.
Segmentation fault (core dumped)

running with debug gives this:
(phy_custom) $ phy template-gui params.py --debug
08:54:46.075 [D] __init__:68          Start capturing exceptions.
08:54:46.650 [D] model:619            Loading spike clusters.
08:54:47.144 [D] model:569            No channel shank file found.
08:54:47.144 [D] model:692            Loading templates.
08:54:47.155 [D] model:724            Templates are dense.
08:54:47.161 [W] model:667            Skipping spike waveforms that do not exist, they will be extracted on the fly from the raw data as needed.
08:54:47.161 [D] model:730            Loading the whitening matrix.
08:54:47.161 [D] model:737            Loading the inverse of the whitening matrix.
08:54:47.163 [D] model:766            Loading features.
08:54:47.163 [D] model:781            Features are sparse.
08:54:47.163 [D] model:803            Loading template features.
08:54:47.171 [D] model:530            Load spike_detection_templates.npy.
08:54:47.199 [D] model:530            Load spike_positions.npy.
08:54:47.200 [D] model:504            Load `cluster_ContamPct.tsv`.
08:54:47.201 [D] model:504            Load `cluster_KSLabel.tsv`.
08:54:47.203 [D] model:504            Load `cluster_group.tsv`.
08:54:47.204 [D] model:504            Load `cluster_Amplitude.tsv`.
08:54:47.467 [D] context:100          Initialize joblib cache dir at `/media/neuropixels/Ya_240415_s2190003_g0/Ya_240415_s219_0003_g0_imec0/kilosort4/.phy`.
08:54:47.467 [D] context:101          Reducing the size of the cache if needed.
08:54:47.469 [D] base:102             Add filter `high_pass`.
08:54:47.469 [D] config:31            Load config file `/home/smithlab/.phy/phy_config.py`.
08:54:47.470 [D] plugin:145           Loading 0 plugins.
08:54:47.471 [D] context:209          The file `/media/neuropixels/Ya_240415_s219_0003_g0/Ya_240415_s219_0003_g0_imec0/kilosort4/.phy/new_cluster_id.pkl` doesn't exist.
08:54:47.596 [D] context:185          Save data to `/media/neuropixels/Ya_240415_s219_0003_g0/Ya_240415_s219_0003_g0_imec0/kilosort4/.phy/spikes_per_cluster.pkl`.
08:54:47.754 [D] gui:463              Creating GUI.
08:54:47.760 [D] state:46             Load /home/smithlab/.phy/TemplateGUI/state.json for GUIState.
08:54:48.689 [D] gui:718              Add view ClusterView to GUI.
08:54:48.694 [D] gui:718              Add view SimilarityView to GUI.
Segmentation fault (core dumped)

And conda list gives this:
(phy_custom) $ conda list
# packages in environment at /home/username/anaconda3/envs/phy_custom:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
abseil-cpp                20211102.0           hd4dd3e8_0  
arrow-cpp                 14.0.2               h374c478_1  
asttokens                 2.0.5              pyhd3eb1b0_0  
aws-c-auth                0.6.19               h5eee18b_0  
aws-c-cal                 0.5.20               hdbd6064_0  
aws-c-common              0.8.5                h5eee18b_0  
aws-c-compression         0.2.16               h5eee18b_0  
aws-c-event-stream        0.2.15               h6a678d5_0  
aws-c-http                0.6.25               h5eee18b_0  
aws-c-io                  0.13.10              h5eee18b_0  
aws-c-mqtt                0.7.13               h5eee18b_0  
aws-c-s3                  0.1.51               hdbd6064_0  
aws-c-sdkutils            0.1.6                h5eee18b_0  
aws-checksums             0.1.13               h5eee18b_0  
aws-crt-cpp               0.18.16              h6a678d5_0  
aws-sdk-cpp               1.10.55              h721c034_0  
blas                      1.0                         mkl  
bokeh                     3.4.0           py311h92b7b1e_1  
boost-cpp                 1.82.0               hdb19cb5_2  
bottleneck                1.3.7           py311hf4808d0_0  
brotli                    1.0.9                h5eee18b_7  
brotli-bin                1.0.9                h5eee18b_7  
brotli-python             1.0.9           py311h6a678d5_7  
bzip2                     1.0.8                h5eee18b_5  
c-ares                    1.19.1               h5eee18b_0  
ca-certificates           2024.3.11            h06a4308_0  
certifi                   2024.2.2        py311h06a4308_0  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.1.7           py311h06a4308_0  
cloudpickle               2.2.1           py311h06a4308_0  
colorcet                  3.1.0                    pypi_0    pypi
comm                      0.2.1           py311h06a4308_0  
contourpy                 1.2.0           py311hdb19cb5_0  
cycler                    0.11.0             pyhd3eb1b0_0  
cyrus-sasl                2.1.28               h52b45da_1  
cython                    3.0.10          py311h5eee18b_0  
cytoolz                   0.12.2          py311h5eee18b_0  
dask                      2023.11.0       py311h06a4308_0  
dask-core                 2023.11.0       py311h06a4308_0  
dbus                      1.13.18              hb2f20db_0  
debugpy                   1.6.7           py311h6a678d5_0  
decorator                 5.1.1              pyhd3eb1b0_0  
distributed               2023.11.0       py311h06a4308_0  
executing                 0.8.3              pyhd3eb1b0_0  
expat                     2.6.2                h6a678d5_0  
fontconfig                2.14.1               h4c34cd2_2  
fonttools                 4.51.0          py311h5eee18b_0  
freetype                  2.12.1               h4a9f257_0  
fsspec                    2023.10.0       py311h06a4308_0  
gflags                    2.2.2                h6a678d5_1  
ghp-import                2.1.0                    pypi_0    pypi
glib                      2.78.4               h6a678d5_0  
glib-tools                2.78.4               h6a678d5_0  
glog                      0.5.0                h6a678d5_1  
grpc-cpp                  1.48.2               he1ff14a_1  
gst-plugins-base          1.14.1               h6a678d5_1  
gstreamer                 1.14.1               h5eee18b_1  
h5py                      3.9.0           py311hdd6beaf_0  
hdf5                      1.12.1               h2b7332f_3  
heapdict                  1.0.1              pyhd3eb1b0_0  
icu                       73.1                 h6a678d5_0  
idna                      3.4             py311h06a4308_0  
importlib-metadata        7.0.1           py311h06a4308_0  
iniconfig                 1.1.1              pyhd3eb1b0_0  
intel-openmp              2023.1.0         hdb19cb5_46306  
ipykernel                 6.28.0          py311h06a4308_0  
ipython                   8.20.0          py311h06a4308_0  
jedi                      0.18.1          py311h06a4308_1  
jinja2                    3.1.3           py311h06a4308_0  
joblib                    1.4.0           py311h06a4308_0  
jpeg                      9e                   h5eee18b_1  
jupyter_client            8.6.0           py311h06a4308_0  
jupyter_core              5.5.0           py311h06a4308_0  
kiwisolver                1.4.4           py311h6a678d5_0  
klusta                    3.0.16                   pypi_0    pypi
klustakwik2               0.2.6                    pypi_0    pypi
krb5                      1.20.1               h143b758_1  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      3.0                  h295c915_0  
libboost                  1.82.0               h109eef0_2  
libbrotlicommon           1.0.9                h5eee18b_7  
libbrotlidec              1.0.9                h5eee18b_7  
libbrotlienc              1.0.9                h5eee18b_7  
libclang                  14.0.6          default_hc6dbbc7_1  
libclang13                14.0.6          default_he11475f_1  
libcups                   2.4.2                h2d74bed_1  
libcurl                   8.5.0                h251f7ec_0  
libdeflate                1.17                 h5eee18b_1  
libedit                   3.1.20230828         h5eee18b_0  
libev                     4.33                 h7f8727e_1  
libevent                  2.1.12               hdbd6064_1  
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libgfortran-ng            11.2.0               h00389a5_1  
libgfortran5              11.2.0               h1234567_1  
libglib                   2.78.4               hdc74915_0  
libgomp                   11.2.0               h1234567_1  
libiconv                  1.16                 h7f8727e_2  
libllvm14                 14.0.6               hdb19cb5_3  
libnghttp2                1.57.0               h2d74bed_0  
libpng                    1.6.39               h5eee18b_0  
libpq                     12.17                hdbd6064_0  
libprotobuf               3.20.3               he621ea3_0  
libsodium                 1.0.18               h7b6447c_0  
libssh2                   1.10.0               hdbd6064_2  
libstdcxx-ng              11.2.0               h1234567_1  
libthrift                 0.15.0               h1795dd8_2  
libtiff                   4.5.1                h6a678d5_0  
libuuid                   1.41.5               h5eee18b_0  
libwebp-base              1.3.2                h5eee18b_0  
libxcb                    1.15                 h7f8727e_0  
libxkbcommon              1.0.1                h5eee18b_1  
libxml2                   2.10.4               hfdd30dd_2  
locket                    1.0.0           py311h06a4308_0  
lz4                       4.3.2           py311h5eee18b_0  
lz4-c                     1.9.4                h6a678d5_0  
markdown                  3.6                      pypi_0    pypi
markupsafe                2.1.3           py311h5eee18b_0  
matplotlib                3.8.4           py311h06a4308_0  
matplotlib-base           3.8.4           py311ha02d727_0  
matplotlib-inline         0.1.6           py311h06a4308_0  
mergedeep                 1.3.4                    pypi_0    pypi
mkdocs                    1.6.0                    pypi_0    pypi
mkdocs-get-deps           0.2.0                    pypi_0    pypi
mkl                       2023.1.0         h213fc3f_46344  
mkl-service               2.4.0           py311h5eee18b_1  
mkl_fft                   1.3.8           py311h5eee18b_0  
mkl_random                1.2.4           py311hdb19cb5_0  
msgpack-python            1.0.3           py311hdb19cb5_0  
mtscomp                   1.0.2                    pypi_0    pypi
mysql                     5.7.24               h721c034_2  
ncurses                   6.4                  h6a678d5_0  
nest-asyncio              1.6.0           py311h06a4308_0  
nspr                      4.35                 h6a678d5_0  
nss                       3.89.1               h6a678d5_0  
numexpr                   2.8.7           py311h65dcdc2_0  
numpy                     1.24.3          py311h08b1b3b_1  
numpy-base                1.24.3          py311hf175353_1  
openjpeg                  2.4.0                h3ad879b_0  
openssl                   3.0.13               h7f8727e_0  
orc                       1.7.4                hb3bc3d3_1  
packaging                 23.2            py311h06a4308_0  
pandas                    2.2.1           py311ha02d727_0  
parso                     0.8.3              pyhd3eb1b0_0  
partd                     1.4.1           py311h06a4308_0  
pathspec                  0.12.1                   pypi_0    pypi
pcre2                     10.42                hebb0a14_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
phy                       2.0b5                    pypi_0    pypi
phylib                    2.4.3                    pypi_0    pypi
pillow                    10.2.0          py311h5eee18b_0  
pip                       23.3.1          py311h06a4308_0  
platformdirs              3.10.0          py311h06a4308_0  
pluggy                    1.0.0           py311h06a4308_1  
ply                       3.11            py311h06a4308_0  
prompt-toolkit            3.0.43          py311h06a4308_0  
prompt_toolkit            3.0.43               hd3eb1b0_0  
psutil                    5.9.0           py311h5eee18b_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pure_eval                 0.2.2              pyhd3eb1b0_0  
pyarrow                   14.0.2          py311hb6e97c4_0  
pygments                  2.15.1          py311h06a4308_1  
pyopengl                  3.1.1a1         py311h06a4308_0  
pyparsing                 3.0.9           py311h06a4308_0  
pyqt                      5.15.10         py311h6a678d5_0  
pyqt5-sip                 12.13.0         py311h5eee18b_0  
pyqtwebengine             5.15.10         py311h6a678d5_0  
pysocks                   1.7.1           py311h06a4308_0  
pytest                    7.4.0           py311h06a4308_0  
python                    3.11.9               h955ad1f_0  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-lmdb               1.4.1           py311h6a678d5_0  
python-tzdata             2023.3             pyhd3eb1b0_0  
pytz                      2024.1          py311h06a4308_0  
pyyaml                    6.0.1           py311h5eee18b_0  
pyyaml-env-tag            0.1                      pypi_0    pypi
pyzmq                     25.1.2          py311h6a678d5_0  
qt-main                   5.15.2              h53bd1ea_10  
qt-webengine              5.15.9               h9ab4d14_7  
qtconsole                 5.5.1           py311h06a4308_0  
qtpy                      2.4.1           py311h06a4308_0  
re2                       2022.04.01           h295c915_0  
readline                  8.2                  h5eee18b_0  
requests                  2.31.0          py311h06a4308_1  
responses                 0.25.0          py311h06a4308_0  
s2n                       1.3.27               hdbd6064_0  
scikit-learn              1.3.0           py311ha02d727_1  
scipy                     1.12.0          py311h08b1b3b_0  
setuptools                68.2.2          py311h06a4308_0  
sip                       6.7.12          py311h6a678d5_0  
six                       1.16.0             pyhd3eb1b0_1  
snappy                    1.1.10               h6a678d5_1  
sortedcontainers          2.4.0              pyhd3eb1b0_0  
sqlite                    3.41.2               h5eee18b_0  
stack_data                0.2.0              pyhd3eb1b0_0  
tbb                       2021.8.0             hdb19cb5_0  
tblib                     1.7.0              pyhd3eb1b0_0  
threadpoolctl             2.2.0              pyh0d69192_0  
tk                        8.6.12               h1ccaba5_0  
toolz                     0.12.0          py311h06a4308_0  
tornado                   6.3.3           py311h5eee18b_0  
tqdm                      4.66.2                   pypi_0    pypi
traitlets                 5.7.1           py311h06a4308_0  
tzdata                    2024a                h04d1e81_0  
unicodedata2              15.1.0          py311h5eee18b_0  
urllib3                   2.1.0           py311h06a4308_1  
utf8proc                  2.6.1                h5eee18b_1  
watchdog                  4.0.0                    pypi_0    pypi
wcwidth                   0.2.5              pyhd3eb1b0_0  
wheel                     0.41.2          py311h06a4308_0  
xyzservices               2022.9.0        py311h06a4308_1  
xz                        5.4.6                h5eee18b_0  
yaml                      0.2.5                h7b6447c_0  
zeromq                    4.3.5                h6a678d5_0  
zict                      3.0.0           py311h06a4308_0  
zipp                      3.17.0          py311h06a4308_0  
zlib                      1.2.13               h5eee18b_0  
zstd                      1.5.5                hc292b87_0

**Comment by zm711** [comment]
Could you try installing with the `environment.yaml`. But as you noted you need to edit it so that `python=3.11`?

**Comment by mattslab** [comment]
> Could you try installing with the `environment.yaml`. But as you noted you need to edit it so that `python=3.11`?

This worked - thank you!

**Comment by zm711** [comment]
Cleaning up fixed issues. Feel free to open new issues if needed :)
