### ISSUE TITLE
[HELP] Time of the waveforms

### ISSUE THREAD

**Issue by EMerinoM14** [cortex-lab/phy#1300]
Hello, I have a question, I think it is easy. 

How much time is represented in the gray line?
I guess we are in millisecond scales but how many milliseconds are represented there?

Thanks

![Screenshot_2](https://github.com/user-attachments/assets/56d0fdaf-5cff-4f9e-bf48-454b30a4d61c)

**Comment by zm711** [comment]
Not quite milliseconds directly. The axis is samples, so it depends on the sample rate of your recording. The two most common amounts are either 61 samples or 81 samples.  So the standard 30,000 sampling rate that many systems use with mean 

61 / 30_000 ~ 0.002 seconds or about 2 ms.

**Comment by zm711** [comment]
Let me know if you need more explanation.
