### ISSUE TITLE
[HELP] peak to trough in miliseconds

### ISSUE THREAD

**Issue by Lorena-J** [cortex-lab/phy#1304]
Hi, I need to calculate the time in ms between peak and trough in a waveform. I have the average of the waveforms and the µV of the peak and valley, but I don't know if there is any file or function to obtain the time from these values.

**Comment by zm711** [comment]
There is not here. You could check out cortex-lab/spikes repo which has some functions in matlab that does that calculation or you could use spikeinterface that calculates many template metrics in python.

**Comment by Lorena-J** [comment]
Thanks!!!!
