### ISSUE TITLE
ISI view

### ISSUE THREAD

**Issue by rossant** [cortex-lab/phy#190]
Code can be shared with the existing CCG view.

**Comment by rossant** [comment]
subplot(i, j) = ISI merge i & j

**Comment by rossant** [comment]
@nippoo @yger this can be something for one of you..

**Comment by yger** [comment]
I ll try to give it a try, modulo understanding the code...

Best

Pierre

Le lun. 3 août 2015 14:55, Cyrille Rossant <notifications@github.com> a
écrit :

**Comment by nippoo** [comment]
@yger you want to do this before SfN or shall I see if I have time?

**Comment by yger** [comment]
Well... To be fair, I won't have time, I'm afraid: I'm already 
overwhelmed in finishing our poster and some simulations, and packaging 
our software into something decent. I would not make this ISI view on 
the top of the priority list, so this is up to you.
As far as I understood after discussions with you guys, key stuffs to 
see in phy would be: amplitudes and templates superimposed onto the raw 
traces. And, of course, for us to be able to use phy on a daily basis 
and then help more to the code itself, not computing all the features 
for all the spikes... The ISIs view is something useful that we are 
using, but you said you are only using the CCs view

Maybe we can talk about it on Friday, if you are around with Cyrille?

Best

Pierre

**Comment by rossant** [comment]
done in the dev branch
