### ISSUE TITLE
Structures for time data

### ISSUE THREAD

**Issue by rossant** [cortex-lab/phy#20]
We need specific data structures to represent temporal data (like in the file format, but for in-memory structures). To be implemented in a specific package `phy.time`.

What are the different types of temporal data?
- time series
- continuous data
- epochs
- ...?
## Structures

We could subclass `ndarray` to represent temporal data.
### Time series

one array + metadata:
- array of times
- unit (second, samples with sampling rate, ...)
### Continuous data

two arrays:
- array of times (irregularly sampled data) or sampling rate
- values
### Epochs

one array + metadata
- a `(2, N)` array with start and end
- unit
### Array of time series

just a Time Series + another array with the indices (e.g. neuron number for every spike)
## Routines

(proposed by Adrien Peyrache)
- Time series: rate, restrict(interval or other time series)
- Continuous data: thresholdInterval(value), meanInterval(interval)
- Epochs: union, intersection, duration, dropShort(ShorterThanThisValue), mergeClose(closerThanThisValue)

Ping @kdharris101 @nippoo Adrien.

**Comment by nippoo** [comment]
Discussion still ongoing. @kdharris101 @rossant
