### ISSUE TITLE
List test datasets

### ISSUE THREAD

**Issue by rossant** [cortex-lab/phy#249]
`phy.utils.datasets.list_test_data()` returns the list of datasets by parsing `http://phy.cortexlab.net/data/`

**Comment by nippoo** [comment]
... Do we want to discriminate between what these bits of test data do?

I mean, we don't want to indiscriminately download ALL the test data. Should we have some metadata?

**Comment by rossant** [comment]
Maybe we can have `test_..._data.md` as well with some notes.

Then, `list_test_data()` shows the list of all datasets and their associated notes.

Ultimately, `download_test_data('test_hybrid')` will download the kwik, kwx, and raw.kwd files.
