### ISSUE TITLE
Name clusters

### ISSUE THREAD

**Issue by nippoo** [cortex-lab/phy#268]
Naming based on natural names (clusternames.csv probably).

Should be able to toggle on/off in user parameters - default is on. Sets a `clusters/clustering_name/cluster_ID/name` attribute in the .kwik...

**Comment by rossant** [comment]
in user_data maybe?

**Comment by rossant** [comment]
also i guess we should have a phy-data repo for big data files like this one (like in vispy)

**Comment by nippoo** [comment]
ehhhhh it's like 200kb. I don't think that's worth the extra hassle of pulling in an extra repo and symlinking in files, tbh

**Comment by nippoo** [comment]
I think just name rather than user_data - consistent with channels/channel_ID/name etc.

**Comment by rossant** [comment]
450kb. sorry i don't want this file in this repo..

**Comment by nippoo** [comment]
well we can put it on phy.cortexlab.net/data/clusternames.csv, and automatically download it at first run of phy, but...

**Comment by nippoo** [comment]
seems like a whole effort - repo size really isn't that much of a problem!

**Comment by rossant** [comment]
we can do that, or do like vispy. we may very well want to add more files eventually

**Comment by rossant** [comment]
yeah it is -- i want to keep repo size as low as possible

**Comment by rossant** [comment]
note that we can reuse the code in utils.datasets or vispy
