### ISSUE TITLE
Requirements testing before install / on run

### ISSUE THREAD

**Issue by nippoo** [cortex-lab/phy#341]
We should test and warn/die as necessary:
- all dependencies exist and are up-to-date (we should define and test minimum versions, linked to #115)
- GPU drivers are supported
- optionally, check latest stable version string off Web somewhere and warn if there's an update available.

We should definitely check all this when launching the cluster GUI, but maybe write some reusable code to check for any subset of this for other modules.

**Comment by rossant** [comment]
Propositions:

* we build a binstar conda package that depends on specific (=latest if possible) versions of numpy h5py etc. Then dependency management is done by conda automatically.
* for GPU drivers we can try to detect if it's Mesa and throw a warning in this case

**Comment by nippoo** [comment]
Yes, but people will always install from git etc, or use WinPython, or OS python, or whatever. Even if it's just people in the lab...

**Comment by rossant** [comment]
hmm, but for dependencies, I'm not really aware of compatibility issues yet, so that's not that urgent.
besides, some dependencies are optional and only loaded when you need them (e.g. PyQt)
maybe we leave this particular one to the moment when we really need it?
