### ISSUE TITLE
plot PCs

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/phy#434]
Would be great to be able to plot the PCs. The most efficient (and useful) way to do this may be to have a hotkey that plots them in the waveform view as if they were three waveforms of three different colors. So each channel has a red, green, and blue waveform on it representing PC1, PC2, PC3. 

[C] and save the PCs in the kwik file too

**Comment by nsteinme** [comment]
Would also be great to see this, along with sample spikes, in the "spike detekt online" view.

**Comment by rossant** [comment]
doable as a plugin
