### ISSUE TITLE
Horizontal split

### ISSUE THREAD

**Issue by rossant** [cortex-lab/phy#471]
Use-case: click to select amplitude min, amplitude max, and create a new cluster out of the selected spikes

**Comment by rossant** [comment]
Also: click to draw polyline, and translate it to select tube of spikes

**Comment by nippoo** [comment]
This is similar to #399 no?

**Comment by rossant** [comment]
Not exactly: this is not the waveform amplitude, but the template amplitude. It will be displayed in a sort of "FeatureView".

**Comment by nippoo** [comment]
Will modify existing split feature allowing option to select whole-width

**Comment by rossant** [comment]
can be done with a polygon lasso in the amplitude view
