### ISSUE TITLE
Integrate probe generation code

### ISSUE THREAD

**Issue by rossant** [cortex-lab/phy#517]
from @neuromusic
- http://www.justinkiggins.com/blog/generating-channel-graphs-for-klustakwik-automatically/
- http://www.justinkiggins.com/blog/defining-large-array-geometries-for-klustakwik/

(see also probe plotting utilities, we can use matplotlib or SVG)

**Comment by neuromusic** [comment]
sweet

**Comment by neuromusic** [comment]
see also https://github.com/gentnerlab/klusta-pipeline/blob/master/klusta_pipeline/probe.py
