### ISSUE TITLE
Wiki page with useful user settings snippets

### ISSUE THREAD

**Issue by rossant** [cortex-lab/phy#614]
For those bits of code that are too specific to be part of the core library

**Comment by nippoo** [comment]
Shouldn't we just build them into phy? We should do this too, but... we should just build them and document

**Comment by rossant** [comment]
it depends... some highly-specific use-cases would be better in the wiki. phy does not intend to implement everything, the goal is to encourage user customization. but no problem to put in phy stuff used by 90% of users
