### ISSUE TITLE
Cluster splitting from TemplateFeatureView

### ISSUE THREAD

**Issue by nikolaskaralis** [cortex-lab/phy#748]
In many instances, it is much easier to split a cluster on the TemplateFeatureView than on the FeatureView. It would be great if the polygon could be drawn on the TemplateFeatureView as well (now it is only possible on the FeatureView).

**Comment by nikolaskaralis** [comment]
On a related note:
Is it possible to have the possibility of drawing connected lines instead of polygons?
The end result would be the same, but the issue with the current method is that the polygon is closed from the beginning which makes it very counterintuitive to create fine polygons.
What I am proposing is that for each click a line connecting the last point with the new one is formed, but the polygon remains open until you click again on the first node.

**Comment by ereming** [comment]
I also have found instances where splitting appears to be straightforward in the TemplateFeatureView. Here is a screenshot of one:
![image](https://cloud.githubusercontent.com/assets/8030712/25240607/42e789e0-25c1-11e7-97d6-ee085989a6ef.png)
There are many spikes assigned to the red cluster which appear to fit better with the blue cluster (or maybe with both) in the TemplateFeatureView. I don't see a similar boundary in the FeatureView.

**Comment by greggheller** [comment]
I've noticed this as well and would be a third person to support splitting in the TemplateFeatureView.

**Comment by rossant** [comment]
done in dev branch
