### ISSUE TITLE
data.shape[-1] must be 1 not 2 for a_box_index

### ISSUE THREAD

**Issue by DanBenHa** [cortex-lab/phy#758]
Hi,

today I spontaneously got this error when I tried to open a Kilosort-sorted session using "phy template-gui params.py":
17:09:31 [E] cli:39               An error has occurred (ValueError): data.shape[-1] must be 1 not 2 for a_box_index
I can open the session just fine on another computer, so it must be related to the installation of phy. Before the error occured I used the development version.
After the error I uninstalled phy and removed the conda environment to reinstall it. But neither the stable nor the development versions work. Reinstalling Miniconda also didn't help (but maybe the uninstall wasn't clean?).

Anybody know how to solve this?

Best wishes, Daniel

**Comment by Schmoba** [comment]
OK, just solved it... There was still a .phy folder in C:/Users/<user> that needed to be deleted...
