### ISSUE TITLE
Advice on analyzing data from the template-gui

### ISSUE THREAD

**Issue by madeleinea** [cortex-lab/phy#761]
Hi,

Everything seems to be working well--I'm using Kilosort and it's sorting my data well. However now I'm at the point where I need to take sorted data from the template-gui and analyze it. Does anyone have any advice on getting numbers like the average waveform peak/valley or spike intervals? After sorting the data manually, we typically used NeuroExplorer to further analyze the data--it would be great if we could continue using that by somehow feeding data from Kilosort to NeuroExplorer. Any advice would be greatly appreciated!

Thanks

**Comment by rossant** [comment]
The dev branch contains a few new views with basic analysis features. We can consider specific new feature requests for ephys data analysis directly in phy, and not necessarily related to manual spike sorting.
