### ISSUE TITLE
WaveformView issue

### ISSUE THREAD

**Issue by shihaisun** [cortex-lab/phy#763]
Hi Phy team,

New user here. I'm having some scaling issues with the WaveformView in TemplateGUI after spike sorting with KiloSort. Basically all of my clusters have very small wave forms that look like flat lines [Screenshot 1]. Increasing the waveform (Ctrl+up) helps with identifying the waveforms [Screenshot 2], however it also produces a mismatch between channel number and average waveform (W shortcut).
Screenshot 1: screenshot of an example cluster with very small wave forms
![capture](https://user-images.githubusercontent.com/30403651/28659655-9531eb30-72f3-11e7-8c40-ca44ce0d916c.PNG)

Screenshot 2: Increasing the waveform with Ctrl+Up shortcut
![asdasd](https://user-images.githubusercontent.com/30403651/28659950-82279110-72f4-11e7-949b-c3049caca65f.png)

Does anyone know how I can fix this?

Thank you for your time,
Scott

**Comment by rossant** [comment]
please reopen if the problem persists in the dev branch
