### ISSUE TITLE
Split units in the waveform, amplitude, and feature template views??

### ISSUE THREAD

**Issue by madeleinea** [cortex-lab/phy#764]
We should be able to split units in the waveform, amplitude, and feature template views. This would be incredibly helpful to finish sorting our data!

**Comment by greggheller** [comment]
I would like to second this, especially splitting in the amplitude view. Sometimes you can accomplish the same thing in the feature view. However depending on the features visibly bi-modal distributions in amplitude view do not always show up in the feature view. 

I'll post a screenshot when I remember to take one.

**Comment by rossant** [comment]
done except in the waveform view, open a new issue if needed
