### ISSUE TITLE
View events and rasters in trace view

### ISSUE THREAD

**Issue by kdharris101** [cortex-lab/phy#765]
We have started using a standard format to represent data associated with neurophys experiments such as behavioral events and timeseries, described [here](https://github.com/cortex-lab/alf2neuroscope).

It would be great if phy could read these and show them in trace view, together with spike rasters. This is a great feature provided by neuroscope, but neuroscope is too slow to show rasters for very large numbers of neurons, and also can't deal with things like unevenly-sampled files that are common in practice.

**Comment by rossant** [comment]
Superseded by #839
