### ISSUE TITLE
FeatureView

### ISSUE THREAD

**Issue by mjk1028** [cortex-lab/phy#767]
Dear,

i have been using phy but from yesterday i do not load (see) data in featureview. i might press something wrong but not sure what causes this and how to go back to the usual setup. i reinstall phy but did not help. do you recognize this and how to load data properly?

thank you so much for your help in advance!

best regards,
MJ

![screenshot_2017-08-12_19-42-45](https://user-images.githubusercontent.com/30392701/29244947-8420c06e-7f96-11e7-9c1a-00ffe71142d5.png)

**Comment by rossant** [comment]
can you check that the pc_features.npy files are present in the directory?

**Comment by irisbhy** [comment]
Hello,
I am having a similar issues with some of my features not displaying properly, including FeatureView and CorrelogramView0. If you were able to solve this problem, please let me know!
and pc_features.npy is in fact in my directory.

Thank you,
Iris

**Comment by rossant** [comment]
please reopen if the problem persists in the dev branch
