### ISSUE TITLE
Phy crashes upon loading data set

### ISSUE THREAD

**Issue by Sarruedi** [cortex-lab/phy#776]
I experience some crashes on some large data sets that were sorted using KiloSort.
The interesting feature of the crash is that I can click on a single cluster upon opening and the program is fine but as soon as I click any other cluster the program becomes non-responsive and has to be killed to close. Does anybody have similar issues with some of their data sets? I did not find a work around yet to manually sort such data sets. Any feedback is appreciated.

**Comment by rossant** [comment]
please reopen if the problem persists in the dev branch
