### ISSUE TITLE
Number of spikes in feature view

### ISSUE THREAD

**Issue by bapungiri** [cortex-lab/phy#780]
Is it possible to increase/change the number of features shown per cluster ? I would like to have an option to show all spikes in the feature view.

**Comment by rossant** [comment]
You should be able to change this by creating a plugin in `~/.phy/phy_config.py`

```python
class MyPlugin(IPlugin):
    def attach_to_controller(self, controller):
        controller.n_spikes_features = 10000
```

see http://phy.readthedocs.io/en/latest/config/

**Comment by bapungiri** [comment]
Unfortunately it didn't work. I also tried deleting the .phy located in the 'params.py' folder, but that didn't change the number of spikes either. Is it possible to add this as a menu option in future relases of phy GUI.

**Comment by rossant** [comment]
done in the dev branch, as a plugin example
