### ISSUE TITLE
Calling status_message from within a plugin

### ISSUE THREAD

**Issue by petersenpeter** [cortex-lab/phy#781]
Hi 

Is there anyway to display a status message from within a plugin? As far as I can see from the documentation, one has to write:

gui.status_message = 'Hello World!'

but an error is given saying that gui is not found. 

Thanks!

/ Peter

**Comment by rossant** [comment]
I think `gui` should be defined if you follow the plugin structure as follows:

https://github.com/kwikteam/phy-contrib/blob/master/examples/custom_view.py

**Comment by rossant** [comment]
this is going to be a plugin example in the upcoming version
