### ISSUE TITLE
Import errors running phy

### ISSUE THREAD

**Issue by hamdanspam** [cortex-lab/phy#783]
I made sure to follow all directions very carefully, and even purged and reinstalled miniconda before attempting an installation (this is my first time trying to install). When I try to run `phy` from my command line on Windows 7, I get an

> ImportError: No module named traitlets.config

I also included an image of my conda terminal's output.

![image](https://user-images.githubusercontent.com/15875720/36931093-35614580-1e7d-11e8-8024-91c806c719f9.png)

**Comment by rossant** [comment]
could you do `pip install traitlets` and try again?

**Comment by hamdanspam** [comment]
umpteenth reinstall and:
![image](https://user-images.githubusercontent.com/15875720/37476204-ee760980-284a-11e8-8096-5c5b7bf32565.png)

**Comment by hamdanspam** [comment]
It looks like it got installed on python2 instead of python 3. Traitlets are installed on python2, but some parts of the installation got routed to the wrong version of python somehow. What can I do to make sure conda installs on python 3?

**Comment by rossant** [comment]
There is a conflict between two installations of Python. Uninstall the one installed in C:\Python27 and try again.
