### ISSUE TITLE
Does not work for single-channel sort

### ISSUE THREAD

**Issue by neurologic** [cortex-lab/phy#784]
Hi,
I have a single channel that I automatically sorted with Spyking-Circus, however I am not able to work with the result of that pipeline in the phyGUI (i get the attached error). Pierre Yger told me that it is a known issue that phyGUI and manual sort cannot handle single-channel right now. Do you know why this is and if there are any temporary work-arounds that I can implement? Are there plans to make this package compatible with single-channel data to view and manipulate the sorts?
Also please let me know if you think I am having a different issue than what I think I am having. 
![capture](https://user-images.githubusercontent.com/4777333/38781071-12361e2a-40ae-11e8-991e-2b9c05749dc8.PNG)

Thank you so much,
Krista

**Comment by rossant** [comment]
is likely to be fixed in the dev branch, reopen if needed
