### ISSUE TITLE
Potential bug with trace view

### ISSUE THREAD

**Issue by Tran0311** [cortex-lab/phy#786]
When choosing a new cluster from clusterview, Phy doesn't automatically highlight the new clusters on the traceview. Instead, traceview still retains the highlight for the previously chosen cluster. A temporary workaround for this issue is to toggle the labels off and on again. Not a very high priority bug I suppose but it's better to let you guys know. Also, while we are on this matter, can we have brighter highlighting? It's a bit hard on the eyes to see the blue spikes among tons of other coloured spikes lol.

**Comment by lshaheen** [comment]
Seconded!

**Comment by rossant** [comment]
fixed in the dev branch
