### ISSUE TITLE
Waveform extraction using python

### ISSUE THREAD

**Issue by Tran0311** [cortex-lab/phy#788]
Hi,

I would like to extract some raw waveforms out of the original data file. From the user guide, I have found this script for matlab:

https://github.com/cortex-lab/spikes/blob/master/analysis/getWaveForms.m

As such, I want to ask if there's a similar script for python users? I have tried to do some translation from matlab into python myself but I haven't been to extract the data from the .dat file properly. The numpy.memmap function did not seem to be able to extract the same data as matlab's memmapfile. It would be great if I can get some advices on this matter.

Best regards,
Tran Tran

**Comment by rossant** [comment]
There is now an [example in the documentation](https://phy.readthedocs.io/en/latest/customization/#examples-of-using-the-api), but it requires the development version in the `dev` branch.
