### ISSUE TITLE
FeatureTemplateView

### ISSUE THREAD

**Issue by claudiagjou** [cortex-lab/phy#791]
Hi, 

I'm new to kilosort and phy and have a couple of questions:

1) Is there any documentation on FeatureTemplateView? If not, could you please explain what is being plotted? 

2) Can FeatureTemplateView be used to determine whether a cluster comes from a well isolated neuron? I've noticed that good-looking waveforms tend to show a complete, oval cluster in FeatureTemplateView, but for smaller waveforms the cluster is often cut off by a straight line or at a right angle. Does a cut-off cluster reflect the fact that the neuron was poorly isolated from background noise? (see screenshot below). 

3) Is there a reason why FeatureTemplateView only displays when two clusters are selected, but it won't display with a single cluster? 

Thanks so much in advance! 

Claudia

![image](https://user-images.githubusercontent.com/40476047/41747373-bb08d63a-757b-11e8-816d-1018f556b916.png)

**Comment by marius10p** [comment]
I answered this one on the Kilosort issues, didn't I?
