### ISSUE TITLE
Error installing plugin

### ISSUE THREAD

**Issue by stephengv** [cortex-lab/phy#792]
We have been trying to add the  [amplitude histogram](https://github.com/kwikteam/phy-contrib/blob/master/phycontrib/views/amplitude_histogram.py) view to our installation of phy but keep running into an error when we launch Phy, that seems to originate with the attempt to load "AsynchCaller".

![image](https://user-images.githubusercontent.com/38478934/41733825-1c912430-7553-11e8-9ae1-9bb9e2506080.png)

Following the instructions, we have edited the config file, and created a plugin folder in the .phy folder, into which we have placed a text file with the plugin's code, and named that file "amplitude_histogram.py".

Any guidance you can provide would be greatly appreciated.

**Comment by rossant** [comment]
Hi, several things you could try after activating the environment, to find out what is the problem:

```
python -c "import phy.gui.qt"
python -c "import PyQt4.Qt"
python -c "from phy.gui import qt"
python -c "from phy.gui.qt import AsyncCaller"
```

and let me know the output of these commands (if they work, they should not return anything, otherwise there will be an error message).

**Comment by stephengv** [comment]
Thanks for the response!

I ran all four of those commands, and all but the final one ran without a error. 

Running:
python -c "from phy.gui.qt import AsyncCaller"
Gave the error: 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'AsyncCaller'

![image](https://user-images.githubusercontent.com/38478934/41857867-733d9ece-7866-11e8-9614-0aded90511ac.png)

**Comment by rossant** [comment]
What versions of phy and phycontrib are you running? If they're not the development versions from GitHub, could you try installing them?

**Comment by stephengv** [comment]
Installing the development version fixed the AsycnhCaller issue! Thanks so much.

I have a few small questions about features present in the development version I am not familiar with from the regular version, but I will create a separate issue for those, in the interest of organization. 

Thanks so much for the help!
