### ISSUE TITLE
Python crashes when trying to open phy template-gui

### ISSUE THREAD

**Issue by clairebee** [cortex-lab/phy#796]
Hello!

When I try to open files using phy, python crashes while/after loading the GUI state.

I have tried 1) deleting state.json 2) reinstalling phy and phycontrib 3) installing the development versions of phy and phycontrib 4) trying to run phy on the sample dataset instead of my own dataset, but unfortunately none of these have worked.

phy was working fine on this computer a few months ago, so this is a relatively recent development...

Any help would be appreciated! :)

Thanks,
Claire 

![image](https://user-images.githubusercontent.com/6329644/43727678-9213385e-999a-11e8-8d41-9fdacf872cdb.png)

**Comment by rossant** [comment]
to reopen if the problem persists in the dev branch
