### ISSUE TITLE
Problem with TraceView and WaveformView

### ISSUE THREAD

**Issue by kevin-allen** [cortex-lab/phy#800]
First, thanks for sharing phy.

I am trying to set up KiloSort and phy on an Ubuntu 18.04 installation. KiloSort runs fine, as far as I can tell. 

I am having problems with the TraceView and WaveformView in phy. See the pictures below.
![screenshot from 2018-09-03 15-16-46](https://user-images.githubusercontent.com/4455059/44989105-17d6c200-af8d-11e8-9ed7-0f08bc5805ab.png)

![screenshot from 2018-09-03 15-20-55](https://user-images.githubusercontent.com/4455059/44989153-36d55400-af8d-11e8-8f1e-270e3be16d06.png)

Some data points go out of scale.

My first suspicion was that something was wrong with the .dat file, but when I open it with neuroscope or other software (my relectro R package) it looks normal (see below).

![screenshot from 2018-09-03 15-22-35](https://user-images.githubusercontent.com/4455059/44989212-7439e180-af8d-11e8-8175-fd2bcf29f231.png)

I have uploaded all configuration files, master file and the .dat file to my google drive if someone wants to try to replicate this problem.
https://drive.google.com/open?id=1ExiikRxrtQBPP0AdPibtG5qadUbvkirU

Any ideas what could be causing the traces to go out of the normal range?

Many thanks for any potential feedback.

**Comment by rossant** [comment]
It might be a fitting problem related to kilosort? If I'm not mistaken, the large vertical lines you see are the residuals, ie the traces minus the templates. Does this happen on other datasets?

**Comment by Sergudx** [comment]
I'm experiencing the same in some of the Kampff Lab recordings (not in all of them). I'm having the problem just when using Kilosort for the clustering (not with Klusta, for example).

Any thoughts on what's going on?

**Comment by rossant** [comment]
please re-open if the issue persists in the dev branch of phy
