### ISSUE TITLE
Output cluster mean waveforms after Phy sorting

### ISSUE THREAD

**Issue by pauline-kerekes** [cortex-lab/phy#807]
Hello,
I am searching for a way to access each cluster mean waveform on every channel after Phy clustering. I have templates.npy which can give an idea of the waveforms after Kilosort clustering, but cluster names change after Phy and so i lose correspondance between cluster names and mean waveform. Having for instance a .npy containing all mean waveform for all clusters on every channel (3 dimensions array) would be ideal. 
Do you know how i could do/access this? 
Thank you very much!
Pauline

**Comment by rossant** [comment]
done in the dev branch
