### ISSUE TITLE
auto-correlogram and waveform nr of spikes 

### ISSUE THREAD

**Issue by tomasaso** [cortex-lab/phy#818]
Hi,

following [Nic's suggestion](https://github.com/kwikteam/phy-contrib/issues/149)  I wanted to increase the number of spikes used to compute the auto-correlogram. 

Unfortunately, I couldn't find where I could do this so I was hoping if you could help me find the correct gui.py file.

Also, would it be possible to increase the number of waveforms displayed for each unit?

Thank you very much for your help,
Tomaso

**Comment by rossant** [comment]
Put this in your `~/.phy/phy_config.py`

```python
from phy import IPlugin
class MyPlugin(IPlugin):
    def attach_to_controller(self, controller):
        controller.n_spikes_waveforms = 100
        controller.n_spikes_features = 2500
        controller.n_spikes_amplitudes = 5000
        controller.n_spikes_correlograms = 100000

c = get_config()
c.TemplateGUI.plugins = ['MyPlugin']
```
