### ISSUE TITLE
 when splitting and merging the user-defined metadata go lost.

### ISSUE THREAD

**Issue by alejoe91** [cortex-lab/phy#826]
When splitting and merging the user-defined metadata go lost. 
Maybe a quick fix could be:
- when merging the metadata is inherited from the cluster with more spikes
- when splitting the metadata of the children is inherited from the parent

Could something like this be easily implemented? :)

Cheers
Alessio

_Originally posted by @alejoe91 in https://github.com/cortex-lab/phy/issues/825#issuecomment-496536501_

**Comment by rossant** [comment]
thanks!
I've implemented something like this in the dev branch, not hugely tested yet. Feedback appreciated!

**Comment by alejoe91** [comment]
pulling now! :)

**Comment by alejoe91** [comment]
seems to be working like a charm
