### ISSUE TITLE
TraceView overlapping spikes are hard to see

### ISSUE THREAD

**Issue by alejoe91** [cortex-lab/phy#827]
Hi @rossant 

In the newest version of phy the overlaid spikes on the trace view are very hard to see.

This is when I zoom in:

![image](https://user-images.githubusercontent.com/17097257/58577033-ee11a980-8245-11e9-8231-c7342a1c27db.png)

This is without zoom:

![image](https://user-images.githubusercontent.com/17097257/58614139-dd018080-82b7-11e9-89df-eb259167452f.png)

You can see some blueish if you really look hard. 
Can you increase the linewidth?

Cheers
Alessio

**Comment by rossant** [comment]
Yes, I've noticed this and I'm not sure why that happens. I'll investigate further
