### ISSUE TITLE
Feature view overflow

### ISSUE THREAD

**Issue by yagui** [cortex-lab/phy#832]
Sometimes, when zooming in, in the feature view, the dots get out of the corresponding box
![1](https://user-images.githubusercontent.com/4296015/59048603-3176a400-8854-11e9-96b8-9f79a99f5462.png)
After zooming in
![2](https://user-images.githubusercontent.com/4296015/59048604-3176a400-8854-11e9-8448-d73062535076.png)
Is not necessary a bug, because sometimes it helps me realize I need to zoom out, although it can be confusing and I don't know if it is the intended behaviour.

**Comment by rossant** [comment]
thanks! fixed
