### ISSUE TITLE
how to reset waveform view

### ISSUE THREAD

**Issue by bfpcruz** [cortex-lab/phy#846]
hey everyone,
I somehow ended up with the waveform visualizer bugged (probably something to do with scale or limits) and i cant seem to get it back to a sensible range. Any way to reset the settings?

![image](https://user-images.githubusercontent.com/7049351/60206149-cd3f7280-984a-11e9-9c82-8681f61f9157.png)

**Comment by rossant** [comment]
I'll add an option soon. In the meantime, delete these 2 files : `~/.phy/TemplateGUI/state.json`, and `.phy/state.json`

**Comment by malinroe** [comment]
Hi, I'm also having this problem (win10). It works for a second if I delete the state.json files, but gets bugged the minute I touch the waveform visualizer.

**Comment by rossant** [comment]
The scaling bug in the waveform view should be fixed in the latest version on dev.
There is no longer a scaling parameter in the feature view at the moment.
