### ISSUE TITLE
ACG doesn't show isi violation within 0.5 ms?

### ISSUE THREAD

**Issue by susuchen66** [cortex-lab/phy#847]
Hi Cyrille,

I'm not sure if this is a bug or actually intended, in both the old version and new version of Phy, the autocorrelogram doesn't show any ISI violation within ~0.5 ms bin. Now with the ISI distribution added to Phy2, you can see in the example attached, there's a significant amount of ISI violation in this unit (as a result of double counted spikes) but all gets removed in ACG. Could you please look into the display? It might be misleading given people taking into account ACG a lot during manual curation. 
A correct ACG plot is also enclosed.
Many thanks!
![phy2](https://user-images.githubusercontent.com/29060635/60387840-8b474400-9a77-11e9-8182-335ef6e8beb5.PNG)
![correctACG](https://user-images.githubusercontent.com/29060635/60387911-26401e00-9a78-11e9-9ccc-0f8de2d8387f.png)

**Comment by rossant** [comment]
At the moment the central peak is removed to avoid the artifacts due to the algorithm but that could be reconsidered, in the meantime does changing the binning to e.g. 0.1 ms fixes the problem for you?

**Comment by susuchen66** [comment]
Thanks Cyrille, after changing the binning to 0.1 ms or 0.2 ms, the central peak would show up.

**Comment by susuchen66** [comment]
Hi Cyrille, could you fix this, since it's misleading to not show the central peak, regardless of which bin size to use. 
Thanks!

**Comment by rossant** [comment]
Yes you're right, this is now fixed on the latest version of phylib. Thanks for your feedback!
