### ISSUE TITLE
Scaling mismatch between raw data and mean and template

### ISSUE THREAD

**Issue by yger** [cortex-lab/phy#850]
This is not crucial, but there is a scaling mismatch in the WaveformView between the raw data and the mean/template. Since it may only be happening for data exported with spyking-circus, maybe something related to the whitening. Is the same behaviour observed in the test data we gave you?

**Comment by rossant** [comment]
Could you post a screenshot with the test data I have, showing which clusters are selected so that I double check?

**Comment by yger** [comment]
Here is one example, but I can give you more. Sometimes, this looks more striking, but I just realized that maybe you are rescaling somehow the data while switching between these plots

![Selection_001](https://user-images.githubusercontent.com/1672447/60791621-55cfe400-a164-11e9-89b4-60555653225a.png)

![Selection_002](https://user-images.githubusercontent.com/1672447/60791707-8021a180-a164-11e9-8d31-027d5f866df0.png)

**Comment by rossant** [comment]
Should be fixed by @mswallac's pull request
