### ISSUE TITLE
Algorithm for "best channel"

### ISSUE THREAD

**Issue by DJ-Hayden** [cortex-lab/phy#853]
Hey! 

I've been pouring through the source code and can't seem to find the place where the "best" channel for a unit/cluster is calculated. I see plenty of calls to get_best_channels(), but that led me to https://github.com/cortex-lab/phy/blob/dev/phy/apps/base.py where it indicates it should be overridden. 

Where is it decided what the best channel for a unit/cluster is?

Thanks!,
Dustin

**Comment by rossant** [comment]
When not using a sparse format for arrays, this is the code that selects the "best" channels:
https://github.com/cortex-lab/phylib/blob/master/phylib/io/model.py#L614
