### ISSUE TITLE
Unsupported OpenGL version on Windows

### ISSUE THREAD

**Issue by siaahmadi** [cortex-lab/phy#856]
Running `phy template-gui params.py` following installation instructions on Windows 10 and Python 3.7.3 gives the following error:

![image](https://user-images.githubusercontent.com/1358088/61570031-05e3fd80-aa3f-11e9-8465-ebf0542ad481.png)

Please help.

**Comment by rossant** [comment]
could you try to install the latest version of your graphics driver

**Comment by siaahmadi** [comment]
> could you try to install the latest version of your graphics driver

I have already done that.

**Comment by rossant** [comment]
What is your graphics card? Do you happen to have both an integrated Intel and a dedicated NVIDIA graphics chipset?

**Comment by siaahmadi** [comment]
I only have the RTX 2070.

![displayadapterproperties](https://user-images.githubusercontent.com/1358088/61974018-5eb11a00-af9a-11e9-8280-f515d55cb49f.png)

**Comment by rossant** [comment]
could you tell me the OpenGL version displayed by the following program: http://realtech-vr.com/admin/glview ?

**Comment by megkirch** [comment]
I am having the same issue. I downloaded the OpenGL Extensions Viewer and I'm using OpenGL version 3.1 with an Intel HD Graphics 3000 renderer. Is there any update on how to resolve this issue?

**Comment by rossant** [comment]
I'm out of suggestions, being unable to reproduce this error on my Windows 10 machine, and not finding much help about this error message online. 
Perhaps try to install `pip install PyOpenGL-accelerate`  but I doubt it would fix the issue.
@rougier have you ever seen this bug with glumpy (my library uses `glumpy.gloo` which is based on PyOpenGL)?

**Comment by rougier** [comment]
No real idea either. Maybe [this thread on stackoverflow](https://stackoverflow.com/questions/40123969/pyopengl-glclearcolor-error-in-windows-ok-in-linux) can help.

**Comment by siaahmadi** [comment]
> could you tell me the OpenGL version displayed by the following program: http://realtech-vr.com/admin/glview ?

My OpenGL Driver version is 26.21.14.3602 (16-Aug-19).

**Comment by megkirch** [comment]
Figured it out - it was as simple as I was plugged into the wrong port on my PC! As soon I switched to the NVidia GPU port everything worked fine. Perhaps others running into this issue may be having the same problem?
