### ISSUE TITLE
polygon location mismatch from cursor position

### ISSUE THREAD

**Issue by HiroyukiKato7** [cortex-lab/phy#857]
When splitting a cluster in the Feature View, there is a location mismatch between where I click and where the polygon is created.  This mismatch is negligible around the center of each plot, but it gets bigger as you click further from the center and that makes it hard to draw polygons in the desired position.

This mismatch exists only in Feature View, and not in Amplitude View or Template Feature View.  I would appreciate it if somebody could fix this.

**Comment by rossant** [comment]
thanks for the bug report, I'll look into it

**Comment by yagui** [comment]
What I found is that you need to click in the middle of the different plots to get a polygon point in the edge. I don't know if this helps to find the bug.
![window](https://user-images.githubusercontent.com/4296015/61806487-c6822c00-ae05-11e9-8f15-1fa32b80ee3d.png)

**Comment by rossant** [comment]
should be fixed in the dev branch
