### ISSUE TITLE
phy startup error on Windows 10 with Anaconda 3

### ISSUE THREAD

**Issue by jlee536** [cortex-lab/phy#858]
Hi all,

I installed phy2 following the official installation documentation with Anaconda 3 in Windows 10. When I try to launch phy by invoking "phy template-gui params.py" after activating phy2 environment, I always get a few error messages as shown in the attached screenshots, seemingly because a few modules are missing, mainly "phy.utils.color", "sklearn", and "phycontrib". I actually installed scikit-learn using conda. BTW, phy still launches once I just keep click "OK" until all the pop-up windows are gone.
What did I miss? How can I remedy those issues? Any help will be greatly appreciated!!

![phy_error_phyutils](https://user-images.githubusercontent.com/45075354/61646878-159b5600-ac7a-11e9-84a4-5769ea208f15.png)

![phy_error_sklearn](https://user-images.githubusercontent.com/45075354/61646885-19c77380-ac7a-11e9-8e84-e4315c925f09.png)

![phy_error_phycontribs](https://user-images.githubusercontent.com/45075354/61646888-1b913700-ac7a-11e9-8173-27416c44e89f.png)

**Comment by angelonc** [comment]
Once you're in the phy environment, try using pip to install the missing modules. (although, it is a bit weird that phycontrib is not found)

**Comment by rossant** [comment]
This is due to an incompatibility with the existing plugins, try to disable them in phy_config

**Comment by rossant** [comment]
closing, please reopen if this hasn't fixed it
