### ISSUE TITLE
Autoscaling in TraceView

### ISSUE THREAD

**Issue by yagui** [cortex-lab/phy#862]
It would be good to be able to disable autoscaling in traceview. When you are navigation trough recordings, sometime a big amplitude artifact make everything super small so you need to rescale, but then when you pass the big amplitude artifact everything is to big so you need to rescale again.

**Comment by rossant** [comment]
+1
something that could also be useful would be to use .1/.99 quantiles or something for better robustness to outliers when autocomputing the scaling

**Comment by rossant** [comment]
done

**Comment by yagui** [comment]
right now is working as I wanted, which is great. Thanks!
Although now I can't go back to the autoscale version. The toggle option is not working for me.
I already tried removing .phy folder in the project folder and ~/.phy/TemplateGUI/state.json and it didn't help.
I prefer this non autoscale version but just so you know, this toggle is not working.

**Comment by rossant** [comment]
do you mean that when you toggle the autoscale, and then move around in the trace view, the view is no longer scaling automatically?

**Comment by yagui** [comment]
yes

**Comment by rossant** [comment]
I couldn't find the problem and it seems to work here. Please feel free to open a new issue with a specific failure example (for example with screenshots) if needed. Thanks
