### ISSUE TITLE
"Wrong" labeling of channels after kilosorting?

### ISSUE THREAD

**Issue by facazevedo** [cortex-lab/phy#864]
Hi,

I am using kilosort2 + phy TemplateGUI v2.0a1 + phylib v2.0a1. My data comes from a linear probe with 16 channels. After sorting with Kilosort2, 3 channels are excluded. The resulting channel_map is [0; 1; 5; 6; 7; 8; 9; 10; 11; 12; 13; 14; 15]. Those channels are also saved in the channel_map.npy. However, when I open phy2, the numbering in the waveform view goes from 0 to 12, instead of displaying the true channel numbers that remained (image attached). Would it be possible to have the original labels of the channels displayed?

Best.

![phy2 (1)](https://user-images.githubusercontent.com/6961250/61889281-2a265b00-aed3-11e9-9049-cac873f8c12b.png)

**Comment by rossant** [comment]
done!

**Comment by facazevedo** [comment]
Thanks a lot!
