### ISSUE TITLE
How to label only best?

### ISSUE THREAD

**Issue by ablot** [cortex-lab/phy#873]
Labelling a cluster (using "L") will apply the label to both best and the closest match. I have the feeling that it wasn't the case before but maybe I just never noticed.

Typically I select a best, press space a bunch of times and decide at the end if I want to add a label, is there a way to easily label only the best without affecting the closest match?

**Comment by rossant** [comment]
The previous behavior might have been unintended as this action should normally act on all currently selected clusters. Perhaps a new action named `label_best` with e.g. shortcut `ctrl+l` would work?

**Comment by ablot** [comment]
That would be perfect but that would override the toggle label. A keyboard shortcut for deselecting all similar would also work (`backspace`?). 
I can also live without, for now I do `up`, `down` to go to the previous best and then back to my current best with no similar select (that's just sometimes a bit slow with bigger datasets).

**Comment by rossant** [comment]
> A keyboard shortcut for deselecting all similar would also work (`backspace`?).

nice idea! I'll do that
