### ISSUE TITLE
[JS:L1629] Uncaught ReferenceError: Table is not defined

### ISSUE THREAD

**Issue by emilyjanedennis** [cortex-lab/phy#876]
using a practice data set from kilosort2 workshop I get this error:
>phy template-gui params.py

js: Uncaught ReferenceError: Table is not defined
10:48:59.497 [E] qt:352               [JS:L1629] Uncaught ReferenceError: Table is not defined

**Comment by rossant** [comment]
If this is happening on a Mac, duplicate of #874.
If not, please reopen!
