### ISSUE TITLE
amplitude sorting doesn't work? 

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/phy#881]
It's weird because it sort of works: units with generally higher amplitude end up higher in the list, or the reverse - but it is not precise. 
![image](https://user-images.githubusercontent.com/7590975/63553002-0b28e200-c4ee-11e9-8ff4-de173b5f87a1.png)

![image](https://user-images.githubusercontent.com/7590975/63553011-12e88680-c4ee-11e9-832a-92430895c860.png)

**Comment by rossant** [comment]
fixed by renaming the duplicate column "amplitude" to "amp"

**Comment by jaib1** [comment]
I still have this issue - I installed phy < 1 month ago according to the [readthedocs](https://phy.readthedocs.io/en/latest/installation/) instructions.

**Comment by rossant** [comment]
there was a conflict between `amplitude` and `Amplitude` but this should have been fixed?!

**Comment by jaib1** [comment]
ah ok, maybe it's because I actually installed phylib directly from pypi instead of github? 
I did 
`pip install phylib` 
instead of 
`pip install git+https://github.com/cortex-lab/phylib.git`
Let me try reinstalling.
