### ISSUE TITLE
Error in the 'WaveformView'

### ISSUE THREAD

**Issue by jiangjinxiang** [cortex-lab/phy#883]
Dear Sir/Madam,
  I met the bug in 'WaveformView' interface as follow:
![image](https://user-images.githubusercontent.com/42309036/63564839-459b8900-c599-11e9-857e-b47a90877ec3.png)
![TIM截图20190823112944](https://user-images.githubusercontent.com/42309036/63564852-50eeb480-c599-11e9-94ff-86e2bd5f208f.png)
  There's no image about spike waveform in TemplateGUI, please kindly help.

**Comment by rossant** [comment]
Could you launch again phy by adding the `--clear-state` command and see if it solved the issue? The scaling of the waveform view might be incorrect and this option would reset it to the default

**Comment by jiangjinxiang** [comment]
> Could you launch again phy by adding the `--clear-state` command and see if it solved the issue? The scaling of the waveform view might be incorrect and this option would reset it to the default

Sir, it has been shown that 'It's not an internal or external command' in phy mode while tpying '--clear-state';

**Comment by rossant** [comment]
okay so you might have an older version of phy. Try doing:

```
pip install --upgrade git+https://github.com/cortex-lab/phy.git@dev
pip install --upgrade git+https://github.com/cortex-lab/phylib.git
```

**Comment by jiangjinxiang** [comment]
> okay so you might have an older version of phy. Try doing:
> 
> ```
> pip install --upgrade git+https://github.com/cortex-lab/phy.git@dev
> pip install --upgrade git+https://github.com/cortex-lab/phylib.git
> ```

Actually, Sir, I have installed the lastest version, and it does not work; and I tried to follow the installation from the 'phy' website (https://phy.readthedocs.io/en/latest/installation/);
I met the notices that there was no 'git' in the python enviroment while doing that conmands (pip install git+https://github.com/cortex-lab/phy.git@dev
pip install git+https://github.com/cortex-lab/phylib.git), so I installed it from 'phy2' enviroment in the Anaconda; Maybe I made some mistakes here?

**Comment by rossant** [comment]
If git is not installed, perhaps it could not install the very latest version. Try doing `conda install git` after having activated the conda environment, and try doing the pip commands again

**Comment by jiangjinxiang** [comment]
> If git is not installed, perhaps it could not install the very latest version. Try doing `conda install git` after having activated the conda environment, and try doing the pip commands again

Sir, I have followed your suggestions, and there is sitll no the '--clear-state' option in the phy

**Comment by rossant** [comment]
What are the output of

```
phy --version
phy template-gui --help
```

**Comment by jiangjinxiang** [comment]
> > If git is not installed, perhaps it could not install the very latest version. Try doing `conda install git` after having activated the conda environment, and try doing the pip commands again
> 
> Sir, I have followed your suggestions, and there is sitll no the '--clear-state' option in the phy.
> 
> ![image](https://user-images.githubusercontent.com/42309036/63635739-bd041200-c698-11e9-8187-1f080a19e308.png)

phy, version 2.0a1

Usage: phy template-gui [OPTIONS] PARAMS_PATH

  Launch the template GUI on a params.py file.

Options:
  --clear-state / --no-clear-state
                                  Clear the GUI state in `~/.phy/` and in
                                  `.phy`.
  --clear-cache / --no-clear-cache
                                  Clear the .phy cache in the data directory.
  --help                          Show this message and exit.

**Comment by rossant** [comment]
The clear state option seems to be available actually, so try to launch the GUI as follows: `phy template-gui params.py --clear-state`

**Comment by jiangjinxiang** [comment]
> The clear state option seems to be available actually, so try to launch the GUI as follows: `phy template-gui params.py --clear-state`

![image](https://user-images.githubusercontent.com/42309036/63636482-7f0beb80-c6a2-11e9-878c-2465e298f4e9.png)


![image](https://user-images.githubusercontent.com/42309036/63636484-86cb9000-c6a2-11e9-8c01-7d10662e70b3.png)


it seem not work,Sir.

**Comment by rossant** [comment]
It seemed that this was not the issue: the raw data file is not available. Therefore, the waveforms cannot be displayed. Try to press "w" on the keyboard several times to see if you manage to see the templates
