### ISSUE TITLE
Raw data in separate directory

### ISSUE THREAD

**Issue by czuba** [cortex-lab/phy#890]
### Issue
When tuning sorting parameters or separately sorting subsets of a larger raw data file (i.e. by channel, or time, or both), its often preferable to have one copy of the raw binary (.dat or .bin) data file stored somewhere outside of the sorting output directory containing all files necessary for Phy to load waveforms.
This allows the sorted output directory to be more mobile (doesn't necessarily drag a complete copy of raw data around with it), and reduces the number of duplicate copies of raw data necessary—_which add up fast when data files reach into the tens-to-hundreds of gigs range._

### Old Solution
Previously, in Phy [one], I dug through the gui initialization stages and found/fixed some old code that seemed written to accommodate this exact scenario; distinct `dat_path` and `dir_path` variables.
From:  **./phy-contrib/phycontrib/template/model.py**, line 173
```
    def __init__(self, dat_path=None, **kwargs):
        dat_path = dat_path or ''
        # Make sure dir_path points to same dir as params.py, and doesn't get stuck wherever the dat_path directory happens to live.
        # NOTE:  your params.py file must have a self referential variable defined as:
        #       dir_path = './'
        dir_path = (op.dirname(op.abspath(op.expanduser(dir_path)))
                    if dat_path else os.getcwd())
        self.dat_path = dat_path
        self.dir_path = dir_path
        self.__dict__.update(kwargs)
```
As the comments mention, this only required a simple addition to the params.py file to include a self-referential `dir_path = './'`

With this in place, it was possible to store raw data separately from the kilosort/phy output directory. In my case, that involved writing the dat_path that shifted a few directories relative to the sorting output directory.  e.g.:
##### When creating output params/files during original sorting:
```
ops.fbinary             = fullfile(dataDir, '..','..', 'raw', [dataFile '.dat']); % the raw dir should be TWO up from this file's kilosort output dir
```
```
% Make params file
% include relative path elements in dat_path
[dat_path, fname, ext] = fileparts(ops.fbinary);
dat_path = split(dat_path, filesep);
dat_path = fullfile( dat_path{find(strcmp(dat_path,'..'),1):end}, [fname ext]);

fid = fopen(fullfile(datafolder, 'params.py'), 'w');
fprintf(fid,['dat_path = ''',dat_path '''\n']);
fprintf(fid,['dir_path = ''.',filesep,'''\n']);
fprintf(fid,'n_channels_dat = %i\n', ops.NchanTOT);
fprintf(fid,'dtype = ''int16''\n');
fprintf(fid,'offset = 0\n');
if mod(ops.fs,1)
    fprintf(fid,'sample_rate = %i\n', ops.fs);
else
    fprintf(fid,'sample_rate = %i.\n', ops.fs);
end
fprintf(fid,'hp_filtered = False'); %??? whats the basis for this hardcoded declaration??
fclose(fid);
```

### Integrating into Phy2
I'm not a python programmer—and definitely not a gui programmer—so I'm having trouble navigating the Phy2 code to find where/how to add this back into the new codebase (to submit as a pull request) is probably far easier/cleaner for someone who actually knows the code.
...likewise, there's probably a simple way to make it gracefully continue in the absence of a 'dir_path' param definition in the params.py file, so the change would be fully backwards compatible.

If this is something that can be added to Phy2, it would be greatly appreciated. ...as an alternative, I've tried using symlinks to raw data, but not all file systems support them (particularly when acquisition/analysis computers span OSes [Win7-10, Ubuntu, OS-X]).

More generally, **Phy2** comprises a really impressive set of improvements on prior functionality & usability, and clearly a lot of thought & work was put into it.
## Thanks for all your hard work!!

**Comment by rossant** [comment]
Hello, in phy2 the `params.py` file accepts a `dir_path` optional parameter which I think should work for you
