### ISSUE TITLE
Wrong TraceView ordering of several probes after spyking-circus sorting

### ISSUE THREAD

**Issue by JoseGuzman** [cortex-lab/phy#893]
Derived from Issue #866 . I will have to reopen the issue for a minor detail. The TraceView channel ordering will not work if phy is called when >1 probes are analyzed simultaneously. This is after using spyking-circus sorted (latest developmental version). 

Attached you can find a screenshot with the most updated developmental version of phy. Channels must be 1-64 ordered in traceView. Note that WaveformView and ProbeView shows the right numeration
![klustaphy](https://user-images.githubusercontent.com/6409964/64676970-f7cac000-d476-11e9-8d42-eb152cb49366.png)

_Originally posted by @JoseGuzman in https://github.com/cortex-lab/phy/issues/866#issuecomment-530259426_

**Comment by rossant** [comment]
Could you send me your dataset? I seem to be unable to reproduce this otherwise

**Comment by JoseGuzman** [comment]
Hi Cyrille,

Thank you very much for your interest. Where do you think I could upload the dataset? Is Dropbox a good option for you?

Best

JOse

JoSe GuZmAn • The Guzman Lab
http://www.guzman-lab.com

Tel.:     +43 678 126 70 96 
Email:  jose.guzman@guzman-lab.com

**Comment by rossant** [comment]
yes that would be perfect, thanks

**Comment by JoseGuzman** [comment]
Hi Cyrille,

[1] the link to the phy files. Please, let me know if you require
other files or further information.

A) You can see that cluster with id=0 and channel=0 has zero amplitudes in
AmplitudeView
B) I also realized that the amp in ClusterView appear 10X larger (they are
correct in AmplitudeView).

I really appreciate your help with these tow issues!. I love Phy!

Best

Jose


[1]
https://www.dropbox.com/sh/wwa4g7zoi14p1zh/AAApvvVxOd6QdjPXW_GKH9U4a?dl=0

**Comment by rossant** [comment]
Thanks! could you upload the raw data file too?

**Comment by JoseGuzman** [comment]
Sure, I've just uploaded a file called cl_continuous.dat. I think I solved the amplitude issue; the sorting program was not reading properly the gain.

**Comment by rossant** [comment]
Fix pushed, is it all working now?

**Comment by JoseGuzman** [comment]
Not really, 
1) the reordering in the TraceView is disorganized. This could be due to the sorting program (spyking-circus)
![TraceView](https://user-images.githubusercontent.com/6409964/66565229-45b01200-eb62-11e9-9b9a-f3212a07d569.png)

2) the cluster with id=0, with channel=0 and depth=0 show zeros even though the amplitudes are ~ 20 uVolts.
![channel0](https://user-images.githubusercontent.com/6409964/66565286-65dfd100-eb62-11e9-9277-4b2c45ffdf1b.png)

**Comment by JoseGuzman** [comment]
Yes, 

```bash
(sorting) segundo.martinez@pcl-imba-3:phylib$ git branch 
* master
(sorting) segundo.martinez@pcl-imba-3:phylib$ git log --oneline -1
ff9dbff (HEAD -> master, origin/master, origin/HEAD) alf export test random generator seed for individual test run
(sorting) segundo.martinez@pcl-imba-3:phylib$ cd ../phy
(sorting) segundo.martinez@pcl-imba-3:phy$ git branch
* dev
  master
(sorting) segundo.martinez@pcl-imba-3:phy$ git log --oneline -1
de013cbd (HEAD -> dev, origin/dev) Move FiringRate.x_max attribute from global state to local state

```

I've just used *`--clear-cache`* and *`-clear-state`* the same happens... maybe I need to re-sort again?

**Comment by rossant** [comment]
For (1), have a look at your `channel_map.npy` file: phy should take this into account when reordering and displaying the channels in the TraceView.
For (2), try to switch to another type of amplitude by pressing `a`

**Comment by JoseGuzman** [comment]
thanks!!!
