### ISSUE TITLE
Channel 0 in ClusterView makes zero the AmplitudeView

### ISSUE THREAD

**Issue by JoseGuzman** [cortex-lab/phy#898]
In the latest developmental Phy2 repository version, I realized that when the maximal amplitude of the spike is in channel 0, the AmplitudeView sets also the amplitudes to zero.  You can see it here in the cluster id==0

![AmplitudeView0](https://user-images.githubusercontent.com/6409964/65434558-4d13b380-de1f-11e9-96be-2873c1151daa.png)

And also when the cluster id is not zero (e.g. cluster id ==1).

![AmplitudeView1](https://user-images.githubusercontent.com/6409964/65434657-77657100-de1f-11e9-993b-1e08e099f6bc.png)

**Comment by JoseGuzman** [comment]
Update; actually, the first (blue) selected cluster always show zero amplitude.
![twoclusters](https://user-images.githubusercontent.com/6409964/65832725-095df580-e2c8-11e9-9524-fd2fe839d9d0.png)

**Comment by dongqin** [comment]
I have the same issue. When I am looking at best and similar channels amplitude together, the amplitude for similar one sometimes collapses to zero. But it didn't happen all the time, probably less than 10% of the situation.
![image](https://user-images.githubusercontent.com/9393894/66171269-8fa27080-e615-11e9-895c-abdf7dd8ed10.png)

**Comment by rossant** [comment]
should be fixed in the upcoming version
