### ISSUE TITLE
warning when selecting cluster

### ISSUE THREAD

**Issue by yagui** [cortex-lab/phy#900]
after updated all the packages through pip, this warning start to appear 3 times everytime I select a new cluster.
 
```
/phy/plot/gloo/variable.py:358: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
data = data.ravel().view([self.dtype])
```

**Comment by yagui** [comment]
strangely, this behaviour is only happening to me with recordings sorted with Kilosort2. The same recordings sorted with Spyking-Circus don't show this behaviour, only two warnings at the beginning and that's it.

**Comment by rossant** [comment]
fixed
