### ISSUE TITLE
Run phy2 on windows subsystem for linux (WSL)

### ISSUE THREAD

**Issue by sina253** [cortex-lab/phy#907]
Hi

I've tried to run the phy2 in the WSL and got the following errors:

![error_phy](https://user-images.githubusercontent.com/17281039/67104132-6c8acb80-f194-11e9-993a-f91b4640fc62.jpg)

**Comment by rossant** [comment]
Do you have a `spike_templates.npy` file in your data directory?

**Comment by sina253** [comment]
Hi
Thank you,
No there was no spike_templates.npy file in data directory.  Now I copied all the files in the data directory. Also installed Anaconda3 and phy2 on the Windows10 directly not on WSL.
Now I get new below error (there is template_features.npy in the data direcory):

![error](https://user-images.githubusercontent.com/17281039/67213091-6b071080-f3eb-11e9-9208-b0e67f742ac7.jpg)
