### ISSUE TITLE
waveform view scaling difference between raw and mean or template 

### ISSUE THREAD

**Issue by tonylien** [cortex-lab/phy#908]
I'm experiencing similar scaling discrepancies between the raw and mean/templates in the waveform view as #850 . I have upgraded to the latest version of phy2 and the problem persists. It seems like units with smaller raw amplitudes have much larger amplitude mean/templates while larger raw units have less discrepancy. 

Small amplitude unit raw, mean, and template:
![phy_screenshot_20191025090638_PlotCanvas](https://user-images.githubusercontent.com/56502035/67587006-c268f180-f707-11e9-83f9-b6c246d58d35.png)
![phy_screenshot_20191025090641_PlotCanvas](https://user-images.githubusercontent.com/56502035/67587007-c3018800-f707-11e9-8492-67a1496c6326.png)
![phy_screenshot_20191025090632_PlotCanvas](https://user-images.githubusercontent.com/56502035/67587005-c268f180-f707-11e9-850c-bd800ea41511.png)

Large amplitude unit raw, mean, and template::
![phy_screenshot_20191025090704_PlotCanvas](https://user-images.githubusercontent.com/56502035/67587030-d3196780-f707-11e9-86f1-1a21b49af113.png)
![phy_screenshot_20191025090708_PlotCanvas](https://user-images.githubusercontent.com/56502035/67587031-d3196780-f707-11e9-85c8-26070317ae8d.png)
![phy_screenshot_20191025090702_PlotCanvas](https://user-images.githubusercontent.com/56502035/67587029-d3196780-f707-11e9-9158-beb66c0ddd46.png)

**Comment by nsteinme** [comment]
Agreed, we also observed this and it seems like a fast and urgent fix - it's very confusing to a lot of people! Thanks @tonylien

**Comment by rossant** [comment]
A partial fix has been pushed, such that the same scaling is used on all types of waveforms, for all clusters. But there's a new problem, which is that the discrepancy between the raw waveforms and the template waveforms is even more apparent. It appears that multiplying the templates by the inverse of the whitening matrix (even though it normally includes the scaleproc parameter of KS2) does not match the raw data. I don't know why. In the meantime, I multiply the templates by a magic value of 20 and it seems to approximately match on the datasets I've tried. We should look more into it to understand where this discrepancy comes from.

**Comment by nsteinme** [comment]
Just to clarify, are these old datasets you have sitting around, or ones
you have run newly through latest ks2?

**Comment by rossant** [comment]
Both

**Comment by rossant** [comment]
cc @marius10p

**Comment by rossant** [comment]
The discrepancy likely comes from KS2, until this is fixed upstream a work-around in phy is to add the line `template_scaling = 20.0` in `params.py` (or with any other scaling factor that empirically works on a given dataset)
