### ISSUE TITLE
alternative amplitude views deactivated?

### ISSUE THREAD

**Issue by marius10p** [cortex-lab/phy#910]
I am in the dev version, and I can no longer cycle through amplitudes, which I assume means there is only one type of amplitude, the one directly provided by kilosort. Previously, Phy2 was computing the "raw" amplitudes and those were very useful to complement the kilosort "template" amplitudes.

**Comment by rossant** [comment]
This is weird, any error message in the terminal? this is a dataset where you have the raw data available, and both waveform view and trace view? Can you cycle through the different types of waveforms as well?

**Comment by marius10p** [comment]
I can cycle through waveforms, and I don't get an error message. Let me
check a different dataset...

**Comment by marius10p** [comment]
What happened was that I had two amplitude views open and it was cycling the primary one. However, the primary amplitude view is nowhere to be found! Together with a few other views. That's why I opened new ones. I attach a screenshot (they are not undocked either). Maybe a button in the drop-down menu to close a view would be good? 

![image](https://user-images.githubusercontent.com/3935246/68484308-00d3d580-020b-11ea-8fe2-5eb73574957f.png)

**Comment by rossant** [comment]
OK, in the meantime you can look at `~/.phy/TemplateGUI/state.json` and change the view_count accordingly. Or just delete this file altogether to reset the default.
