### ISSUE TITLE
missing phy2 waveform

### ISSUE THREAD

**Issue by boubenec** [cortex-lab/phy#911]
Hi,
I'm doing my clustering with klusta. For some reasons, when I open the .kwik file with phy2 (phy kwik-gui), I miss the waveforms (all channels are flat), although all the other panels (trace, correlogram, features and so forth) work normally for any selected cluster.
Contrary to the message of nmtimme 2 days ago, the behavior of phy is normal for the test kwik data.
Thanks for the help. Cheers, Yves.

**Comment by rossant** [comment]
Could you delete the `~/.phy/` directory in your home directory, as well as the .phy subfolder in your data directory, and try again? It might be a bad waveform scaling issue.

**Comment by boubenec** [comment]
Amazing, it's working. The waveforms are displayed! Thanks sooo much. Yves.
