### ISSUE TITLE
Problem installing PHY2 on a Windows10 machine

### ISSUE THREAD

**Issue by lalittaSA** [cortex-lab/phy#912]
Hi, 
I've to install PHY2 on a new computer but once I completed all the processes and wanted to open a file, I got these error messages. What did I do wrong? Can there be version issue?

Thanks for your support,
Lalitta
![2019-11-08 (1)](https://user-images.githubusercontent.com/24767451/68449351-616a0f00-0219-11ea-8b2d-20ae3ac0546d.png)
![2019-11-08 (2)](https://user-images.githubusercontent.com/24767451/68449352-616a0f00-0219-11ea-8ab7-68f942a270a9.png)
![2019-11-08 (3)](https://user-images.githubusercontent.com/24767451/68449354-6202a580-0219-11ea-86b9-fb7936652ee3.png)
![2019-11-08 (4)](https://user-images.githubusercontent.com/24767451/68449355-629b3c00-0219-11ea-969e-1a17c3b0fb97.png)

**Comment by rossant** [comment]
It does look like a conflict between multiple versions. Ensure that all previous versions are uninstalled, and delete ̀~/.phy` in your home directory, as well as the .phy subfolders that may exist in your data directories.

**Comment by lalittaSA** [comment]
Thank you for your reply. Now I get another error message regarding python version. Just to confirm, do I need Python 2.7, right? (I installed Anaconda 3 and PHY complained).

Many thanks,
L

**Comment by lalittaSA** [comment]
Forgot the screenshot.

![2019-11-15](https://user-images.githubusercontent.com/24767451/68914956-e1045a80-0792-11ea-9983-9d266a023824.png)

**Comment by lalittaSA** [comment]
I removed everything and reinstalled Anaconda and PHY2 from scratch but still got the same issue.
Which Python version is installed in your virtual env, please? I tried python 3.7 and 3.6 they gave the same error message (that I was trying to read with python 3 a joblib pickle generated with python 2, as shown in the above screenshot). However, with python 3.5, I got a different error message regarding the path (see screenshot). Any suggestions? 

Thank you so much
![20191119 PHY2-py35](https://user-images.githubusercontent.com/24767451/69074979-05965600-0a63-11ea-9491-3a448dca52bb.png)

**Comment by rossant** [comment]
I use Python 3.7. It seems that the .phy subfolder was not properly removed. Make sure you enable the display of system and cached folders in your explorer settings? The directory you want to delete is `I:\kiloSorted\MrCassius-190324\D1_PFC_R1\KS2_7\.phy`.

**Comment by lalittaSA** [comment]
Ohh!! Now it works. I thought I was supposed to remove .phy just in the folder I installed Anaconda. Thank you so much again for your kind support.
