### ISSUE TITLE
waveforms in only few channels on PHY2

### ISSUE THREAD

**Issue by lalittaSA** [cortex-lab/phy#919]
![20191121 PHY2-waveformIssue](https://user-images.githubusercontent.com/24767451/69323326-1cae9100-0c79-11ea-85fd-ad59265f0a70.png)
Hi,

I got PHY2 working now. But I don't have the waveforms properly displayed. I always got 2 channels and the other ones are flat. I tried removing ./phy folders everywhere but it didn't solve the problem.

Thanks for your help!
Lalitta

**Comment by rossant** [comment]
Could you send me your dataset?

**Comment by lalittaSA** [comment]
Thanks for you reply. Do you mean the whole folder with raw data? It's ~25GB.
What would be the best way to transfer it to you?

**Comment by rossant** [comment]
Yes but you can not send the raw data (just give me its exact file size in bytes)
I also don't need the `.phy` subfolder
You could use dropbox or google drive?

**Comment by lalittaSA** [comment]
I've compressed the folder (except the raw data) and sent it to you through DropSend (My dropbox folder doesn't have enough space).

Thanks again for your help.

**Comment by rossant** [comment]
fixed in the latest version

**Comment by lalittaSA** [comment]
Many thanks again, Cyrille!
L
