### ISSUE TITLE
Template Gui Distorted and unusable in Windows 10

### ISSUE THREAD

**Issue by jmhasse01** [cortex-lab/phy#922]
My apologies if this sort of thing has been addressed before. Running the template-gui command opens a GUI which is distorted and unusable (see images below). This machine is a laptop with 32gb RAM and an Nvidia GTX 1660. I can run the template-gui command on a desktop on the same files and it works perfectly (see images below). 

I followed the installation instructions on both machines. I'm also running Anaconda3 on both machines. I'm worried that there is a display issue with the laptop, possibly between the integrated graphics card and the dedicated graphics card. I've also included the --debug output for both cases. Any help is appreciated!

Thanks,
Mike

Distorted GUI:
<img width="1920" alt="template-gui_distorted" src="https://user-images.githubusercontent.com/16565055/69759444-2419e280-1130-11ea-8edb-17af057f28b1.PNG">

Distorted GUI debug:
<img width="953" alt="template-gui_distorted_debug" src="https://user-images.githubusercontent.com/16565055/69759462-33009500-1130-11ea-8760-fc8890b37524.PNG">

Good GUI:
<img width="1772" alt="template-gui_good" src="https://user-images.githubusercontent.com/16565055/69759482-3bf16680-1130-11ea-96f6-9a64680ecdf9.PNG">

Good GUI debug:
<img width="933" alt="template-gui_good_debug" src="https://user-images.githubusercontent.com/16565055/69759502-457ace80-1130-11ea-9ed5-b7cf7ff430c6.PNG">

**Comment by subhacom** [comment]
Can confirm same problem on a Windows 10 laptop with 16 GB RAM and NVIDIA GeForce  GTX 1050 Ti graphics card.

**Comment by jmhasse01** [comment]
Ok, I was able to solve the distortion problem by forcing Powershell to run from the discrete graphics card in the Nvidia Control Panel. Running from the integrated graphics card causes distortions in the GUI.

**Comment by rossant** [comment]
Thank you for letting us now @jmhasse01 
How did you force Powershell to run from the discrete GPU?

**Comment by jmhasse01** [comment]
I used the Nvidia control panel: right click on Desktop>Nvidia Control Panel>Desktop> 'Add "Run with Graphics Processor" option'. Then I was able to right click on the Powershell shortcut and select which graphics card to use. 

I'm guessing there's a way to set the discrete graphics card as the default for Powershell, but I haven't figured out how to do that yet.

**Comment by subhacom** [comment]
Thanks for sharing this, it solves the problem. 

After enabling the "Run with graphics processor" menu option, this appears as a submenu in the right-click pop-up menu. After expanding that submenu, it shows the list of GPUs to choose from, and then at the bottom of the list "Change default graphics processor" which is supposed to do that.

Another way I found was to go to 3D-settings in NVIDIA control panel, select "Manage 3D settings" in the menu tree on the left, and then go to "Program settings" tab. One can set the preferred GPU for individual programs here.

**Comment by R-Norris** [comment]
Thank you for sharing these solutions, I ran into a similar issue with distorted or blank view windows on a Windows 10 machine and this thread has been very helpful. 

I just wanted to add that with the recent May 2020 update (20H1), there is no longer a “Run with graphics processor” option in the NVIDIA Control Panel. The solution that worked for me was to go into the Windows settings > System > Display > Graphics Settings and then use Browse to add phy and Options to select the NVIDIA GPU. This forces Windows to run phy through the selected GPU and fixed all the display issues I was having.
