### ISSUE TITLE
Display of TraceView and WaveformView for parallel probes.

### ISSUE THREAD

**Issue by JoseGuzman** [cortex-lab/phy#928]
If I understand correctly, [Phy](github.com/cortex-lab/phy/) plots the **WaveformView** based on the probe file, and it takes the largest y-coordinate to plot it above and the smallest y-value to plot down (*). I have a probe file whose (x,y) coordinates go downward from [0,0] to say, [35,-305]. While the geometry of the probe is preserved, the channel numbers in **TraceView** _are in the opposite direction_ than in **WaveformView** (see figure). 

![TraceViewWrong](https://user-images.githubusercontent.com/6409964/70919680-92600f80-2021-11ea-897c-2abbc20e76b7.png)

When I tried to set the coordinates in positive values (in the previous example, from [0,0] to [35,305], the geometry of the probe is upward and this time, the TraceView is correct, but the WaveformView is in the opposite direction (see figure below). Also, channels of a different probe appear (see rosa marks). Am I missing something?
![TraceViewWrong2](https://user-images.githubusercontent.com/6409964/70921155-0b606680-2024-11ea-8922-8f061c2139c2.png)

I was wondering what is the way Phy plots **TraceView** and **WaveformView**, because due to the reasoning above (*) it will be difficult to visualize parallel probes. Is it because Phy is oriented towards linear probes?. Would it be possible to arrange parallel probes (e.g., four linear probes), and have the channels simply oriented from 1 to n downwards in the **TraceView** but keeping the geometry in **WaveformView**?

Thanks in advance!

Jose

**Comment by rossant** [comment]
There should be an option in the trace view to switch the origin (view menu, trace view, switch origin), does it work?

**Comment by JoseGuzman** [comment]
Yes, ALT+O. It's embarrassing that  I missed it. Thank you very much.
