### ISSUE TITLE
Horizontal line on ACG

### ISSUE THREAD

**Issue by niranjankambi** [cortex-lab/phy#929]
Hi, 
![image](https://user-images.githubusercontent.com/14698586/71648171-8c775900-2cc6-11ea-9994-94dc2f52361d.png)
Can you please let me know what the horizontal line near the abscissa in the ACG plot (e.g shown above) indicate as I did not find any info about it in the manual.
Thanks,
Niranjan

**Comment by rossant** [comment]
This is the baseline firing rate of the neuron
