### ISSUE TITLE
bug on similarity view

### ISSUE THREAD

**Issue by rtomioka** [cortex-lab/phy#932]
Hi,

We recently started to use Kilosort&phy to do clustering units.
Although it might be the major bug, I just want to know whether the bug is not serious.

We found the bug on similarity view.
When I chose cluster133, I could find cluster 2 on the similarity view.
![cluster133](https://user-images.githubusercontent.com/59864591/72326944-808e8c80-36f3-11ea-9ca8-931dda59dcb0.png)

But when I chose cluster137, I missed cluster 2 on the similarity view.
![cluster137](https://user-images.githubusercontent.com/59864591/72327063-b9c6fc80-36f3-11ea-812a-965970119d95.png)

Please let me know whether it is major problem or not.
Best,
Ryohei

**Comment by rossant** [comment]
I suggest you sort the similarity views by decreasing similarity, by clicking on the "similarity" column header.

Also you should know that only the most similar clusters are shown in the similarity view, so in general you cannot expect the displayed similarity matrix to be symmetric.

**Comment by rtomioka** [comment]
Hi,

Thank you for your quick reply.
I got your idea.

Best,
Ryohei
