### ISSUE TITLE
Option to toggle labels in probe view

### ISSUE THREAD

**Issue by balefebvre** [cortex-lab/phy#933]
Hello,
I've updated Phy today and it's working like a charm. I've noticed that the probe view now displays some labels. However, with a small screen, these labels fill the view:
![phy_probe_view](https://user-images.githubusercontent.com/2544801/72440900-ffde9780-37a9-11ea-8ed4-38660cb3c273.png)
Could you please add an option to hide these labels?

**Comment by rossant** [comment]
oups! sorry, just pushed a fix

**Comment by balefebvre** [comment]
Just pulled the fix. It does the job. Thanks!
