### ISSUE TITLE
Changing average waveform line thickness

### ISSUE THREAD

**Issue by dervinism** [cortex-lab/phy#936]
Could you please advice me how to change the line thickness of the average waveform in the WaveformView? Do you have a plugin example for that purpose? Thanks

**Comment by rossant** [comment]
Is it too thin or too thick? The very latest version on the dev branch of phy should show a thicker line than before

**Comment by dervinism** [comment]
I am currently using the latest dev version and it is too thick. I had a regular version installed earlier but the FeatureView was not functioning properly.

**Comment by rossant** [comment]
Okay, I'll add an option to change the width

**Comment by rossant** [comment]
fixed in the next release
