### ISSUE TITLE
FeatureView Ctrl+/- functionality stops working

### ISSUE THREAD

**Issue by dervinism** [cortex-lab/phy#941]
I noticed that FeatureView stop working properly soon after starting Phy. In particular, Ctrl+ and Ctrl- would affect the zoom of data points in grey but not the ones appearing in colour. This affects both dev and regular versions.

**Comment by rossant** [comment]
I can't reproduce the problem. What is your OS? Do you have the same problem if you run phy with the `--clear-state` and `--clear-cache` options from the command line?

**Comment by dervinism** [comment]
I'm using Windows 10. It works fine again after restarting Phy but quickly the same problem occurs. However, now I noticed that by Ctrl clicking a channel in the WaveformView fixes the issue with the FeatureView.

**Comment by rossant** [comment]
any error message in the terminal?

**Comment by dervinism** [comment]
No error messages with --debug

**Comment by rossant** [comment]
to reopen if reproduced
