### ISSUE TITLE
Mismatch between amplitudes in the WaveformView and AmplitudeView

### ISSUE THREAD

**Issue by dervinism** [cortex-lab/phy#942]
There often seems to be a mismatch between amplitudes in the WaveformView and AmplitudeView.
![github](https://user-images.githubusercontent.com/50549306/72727574-27a37600-3b83-11ea-8ed9-07c83e6b1deb.png)

**Comment by rossant** [comment]
You see the same thing if you switch amplitude type by pressing "a" several times?

**Comment by dervinism** [comment]
The AmplitudeView changes. I can see that the scale changes as well. What does pressing "a" do? Does it flip between different recording channels?

**Comment by dervinism** [comment]
Oh, I see it is indicated in the bottom left corner. So the maximum recording channel is based on the blue waveform, I pressume.

**Comment by rossant** [comment]
yes, see https://phy.readthedocs.io/en/latest/visualization/#different-types-of-amplitudes

**Comment by dervinism** [comment]
And I can change the channel by Ctrl clicking. That's good to know. Thanks
