### ISSUE TITLE
incorrect waveform view and probe view 

### ISSUE THREAD

**Issue by rajatsaxena** [cortex-lab/phy#949]
I am seeing incorrect waveform view and probe view when I load the kilosort output data. 

![Capture](https://user-images.githubusercontent.com/5181888/73779509-b0084600-4741-11ea-93b6-7dd1e83f779a.PNG)

This is the channel map scatter plot generated using `channel_positions.npy`. This map matches our input channel map to the kilosort.
![Figure_1](https://user-images.githubusercontent.com/5181888/73779510-b0a0dc80-4741-11ea-8103-e81b75df87df.png)

I have tried deleting the `.phy` folder and refreshing the views but nothing. This problem exists surprisingly for only this specific dataset. Other datasets with different channel map load without any issues.

**Comment by rossant** [comment]
Does the problem still occur whether you add `show_mapped_channels = False` or `True` in your `params.py`, and delete the `.phy` subdirectory, and if you use the latest version of phy and phylib on GitHub?

**Comment by rajatsaxena** [comment]
updating the version fixed the issue but now switching to different clusters leads to display of incorrect waveforms and crashing of phy without any error message

**Comment by rossant** [comment]
Okay then could you send me your dataset? If there is an issue with the raw waveforms, I will need the raw data as well. Thanks.

**Comment by rajatsaxena** [comment]
Hi, I have added all the data here:
https://drive.google.com/drive/folders/1-JRdNN_A2GkB11iX89HhTYreVxjIwqXy?usp=sharing

**Channel map**
![Figure_1](https://user-images.githubusercontent.com/5181888/73888800-27fa6d00-4823-11ea-9313-3325172230b8.png)

**Phy output**
![1](https://user-images.githubusercontent.com/5181888/73888810-2b8df400-4823-11ea-90d1-8ba05bbb3628.png)

**Comment by rajatsaxena** [comment]
I just redid all the installation after downloading the repository rather `pip install` and everything seems to be back to normal. Thank you so much for your time.
