### ISSUE TITLE
residual spikes after the end of the recording?

### ISSUE THREAD

**Issue by scally12** [cortex-lab/phy#953]
I am new to kilosort and phy2. I am going to change spike sorting program to kilosort from the Plexon offsorter.
My recoding system is 128 channels TDT system. First, I sorted with kilosort2 and tried to use phy2 to check the sorting. When I run phy2, I see as 
[W] model:395 There are 9850901/18195593 spikes after the end of the recording.
I am wondering whether it is an error of reading the rawdata or something else.
Could you help me out, please?

**Comment by scally12** [comment]
I got it. It's related to the raw data. Thanks.

**Comment by lachioma** [comment]
> I got it. It's related to the raw data. Thanks.

Could you please explain, I am also wondering...
Thank you!

**Comment by ensorpalacios** [comment]
I run KS3 and everything alright. I then run KS2 on same dataset and now whenever I try to visualise KS3 data with phy I get this error too. Any idea why?
