### ISSUE TITLE
Problems in display - waveform view and feature view

### ISSUE THREAD

**Issue by Oryud** [cortex-lab/phy#967]
Hello all,
I worked on my recordings on phy1, then moved to another computer with phy2.
Unfortunately, something is wrong with the waveform view and probably with the feature view as well, and they look completely different from how they looked in phy1, as if it is not alligned correctly so everything looks like noise - see attached images.
I guess this is a display problem. Does anyone know how to solve this?

Thanks a lot!
Or
![Ph1_id5](https://user-images.githubusercontent.com/61749097/75863613-6dea2700-5e09-11ea-9ac4-fd7cdcc6c85b.JPG)
![Ph1_id10](https://user-images.githubusercontent.com/61749097/75863616-6fb3ea80-5e09-11ea-98ac-55b8cc4ace0e.JPG)
![Phy2_id5](https://user-images.githubusercontent.com/61749097/75863618-6fb3ea80-5e09-11ea-8bdf-094da8a6a3f1.JPG)
![Phy2_id10](https://user-images.githubusercontent.com/61749097/75863619-704c8100-5e09-11ea-80d9-6b4372cacae1.JPG)

**Comment by rossant** [comment]
I think you need to update phy and phylib to the latest versions on GitHub

**Comment by Oryud** [comment]
This seems to do the trick. Thank you so much!
