### ISSUE TITLE
Channel selection returns to default after zooming in/out in FeatureView

### ISSUE THREAD

**Issue by dimokaramanlis** [cortex-lab/phy#968]
I don't know whether this is intended, but this issue is about selecting two channels in WaveformView in order to examine their principal components in FeatureView. In particular, if one tries to zoom in or out in FeatureView (e.g. with Ctrl + scrolling), then these two channels return to their default values.

**Comment by rossant** [comment]
thanks for the bug report, should be fixed on dev
