### ISSUE TITLE
How to adjust width of highlighted interval around spike in TraceView

### ISSUE THREAD

**Issue by hana777** [cortex-lab/phy#973]
Hello everyone,

Is there a way to change the width of the interval that is highlighted around the spikes in TraceView?As it is, I find it hard to distinguish between spikes that occur shortly after each other and would therefore like to make it more narrow. 
Is there a plugin for this that I can install or do you have any advice on how to write one?  I think variable t in the _plot_spike function in phy\cluster\views\traces.py should be adjusted for this, but I do not yet have enough programming experience to figure out the correct approach. Any help would be really appreciated.

Thanks in advance!

![phy_screenshot_20200311095835_TraceView](https://user-images.githubusercontent.com/35686767/76399920-c4161780-637f-11ea-8c59-2abbd8092954.png)

`
        
        
            
          

    def _plot_spike(self, bunch):
        # The spike time corresponds to the first sample of the waveform.
        n_samples, n_channels = bunch.data.shape
        assert len(bunch.channel_ids) == n_channels

        # Generate the x coordinates of the waveform.
        t = bunch.start_time + self.dt * np.arange(n_samples)
        t = np.tile(t, (n_channels, 1))  # (n_unmasked_channels, n_samples)

        # Determine the spike color.
        i = bunch.select_index
        c = bunch.spike_cluster
        cs = self.color_schemes.get()
        color = selected_cluster_color(i, alpha=1) if i is not None else cs.get(c, alpha=1)

        # The box index depends on the channel.
        box_index = self.channel_y_ranks[bunch.channel_ids]
        box_index = np.repeat(box_index[:, np.newaxis], n_samples, axis=0)
        self.waveform_visual.add_batch_data(
            box_index=box_index,
            x=t, y=bunch.data.T, color=color,
            data_bounds=self.data_bounds,
        )
`

**Comment by rossant** [comment]
Thanks for your feedback. This will be fixed in the upcoming version.
