### ISSUE TITLE
possible suggestion: additional packages needed for installation when using .kwik data

### ISSUE THREAD

**Issue by reinderdorman** [cortex-lab/phy#975]
We noticed on several windows machines, using kwik-gui with .kwik files, that we need to install a few more packages that are not installed in the installation instructions. We did did just by using pip install, and it seems to work fine. I'm not sure if this is a bug? Otherwise I'd suggest this to be added to the instructions? These packages are:

klusta
klustakwik2

klusta seems to be needed to get the necessary KwikModels, and I would think this is related to use stuff clustered with klusta? And klustakwik2 is required when re-clustering a (set of) clusters during manual spike-sorting.

**Comment by rossant** [comment]
Thanks. Instructions soon to be updated...
