### ISSUE TITLE
Issue with GUI launching - probably openGL / graphic driver update related

### ISSUE THREAD

**Issue by qcad017** [cortex-lab/phy#977]
Hi,

About a week ago my Phy2 gui stopped launching properly. The main window will show up but w/ parts of the sub-windows just being white blocks. Same problem occurred to one of my colleagues. With the problem, Phy2 still responds to clicks or drags more or less normally; it's just not showing properly on the screen. No error message was there in terminal. Re-starting or re-installing didn't make any difference.

Around about the same time Matlab reported a plotting failure calling openGL and requires me to update my graphic driver (which, on the other hand, was already the latest version). I thus suspect they are caused probably by a similar issue.

Currently the issue is solved by downgrading my graphic driver to an older version.

I'm using a built-in Intel UHD graphic card. The problem (for both Matlab and Phy2) occurred over night. It's possible that something in the driver is updated and caused a incompatibility with the codes (I guess?).

Kilo

**Comment by rossant** [comment]
There are known issues with some Intel drivers on Windows. Could you have a look at [this thread](https://github.com/cortex-lab/phy/issues/957#issuecomment-594896788) and try to see if you're able to install the version of the driver that may include the fix?
