### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by AhnafHassan** [cortex-lab/phy#978]
Hi, 

I have been using Kilosort and Phy2 for a few months. But today when I was trying to open Phy2, I kept getting the following error messages. 

![image](https://user-images.githubusercontent.com/31809185/76670289-1ca70980-6566-11ea-8ce9-74c2d965379a.png)

Unfortunately, the command "phy template-gui params.py --debug" yields the same error message. Kindly help me out. Thanks in advance. 

Sincerely,
Ahnaf

**Comment by rossant** [comment]
Hi, it seems you're using the dev branch of phy. I'd suggest to switch to the master branch which is now the stable one.
The alternative is to install the dev branch of phylib as it is required by the dev branch of phy.

**Comment by AhnafHassan** [comment]
Hi Rossant, 

Thank you for your response. So, to solve this, I basically need to type this: 
pip install git+https://github.com/cortex-lab/phy.git@master

instead of pip install git+https://github.com/cortex-lab/phy.git@dev

Is that correct? Thank you in advance. 

Sincerely, 
Ahnaf

**Comment by rossant** [comment]
Yes. You might need to add `--upgrade` at the end of the command as well. Let me know if that worked.

**Comment by AhnafHassan** [comment]
Yep, that solves it. Thanks.
