### ISSUE TITLE
Problem with visualizing the waveform in waveformview Phy

### ISSUE THREAD

**Issue by fveen** [cortex-lab/phy#983]
Can't get the waveform view to work normally I can't visualize the waveform. But in the meantime I'm not getting an error.  Had the same problem with phy2 so now installed the older phy instead.  But get the same problem here. All the other views function well. Does anyone know how to fix this? reset this?

**Comment by rossant** [comment]
Could you post a screenshot of the entire GUI?

**Comment by fveen** [comment]
![gui](https://user-images.githubusercontent.com/62026405/77444141-d36b7b00-6deb-11ea-8ab6-c4670811252d.png)

**Comment by rossant** [comment]
Thanks. Could you delete ~/.phy/KwikGUI/state.json and try again?

**Comment by fveen** [comment]
![remove](https://user-images.githubusercontent.com/62026405/77450129-25fc6580-6df3-11ea-8c47-91e19e180d21.png)

**Comment by rossant** [comment]
do this instead:

`del c:\users\felic\.phy\KwikGUI/state.json`

**Comment by fveen** [comment]
Thank you for your help! Then I get this error:

(kk_ff) C:\Users\felic\OneDrive\Documenten\RD\Klusta_Probe1_15012020>del c:\users\felic\.phy\KwikGUI/state.json
Parameter format not correct - "state.json"

**Comment by rossant** [comment]
sorry I did a mistake, do this instead:

`del c:\users\felic\.phy\KwikGUI\state.json`

**Comment by fveen** [comment]
Yes worked and Gui does look different, but after some trying still can't get the waveform right:

**Comment by fveen** [comment]
![gui2](https://user-images.githubusercontent.com/62026405/77452675-8214b900-6df6-11ea-89ec-5313118240d7.png)

**Comment by fveen** [comment]
![gui2](https://user-images.githubusercontent.com/62026405/77452729-90fb6b80-6df6-11ea-8ae4-6faaaee79b4f.png)

**Comment by rossant** [comment]
Okay  there may be something wrong in the file. Do you have a way to send me your dataset? (kwik and kwx files) via dropbox or similar?

**Comment by fveen** [comment]
I wish it was that..but the same file works fine on another computer.
