### ISSUE TITLE
Phy2 GUI freezes cluster display

### ISSUE THREAD

**Issue by mari-sosa** [cortex-lab/phy#984]
I'm using phy2 on Ubuntu 18.04 (installed using pip) and am having a graphics issue where partway through the session, the views will get "stuck" on a single cluster and fail to update when I select new clusters.  

This is the cluster I was viewing before the freeze (cluster 2):
![Screenshot from 2020-03-24_cluster2accurate](https://user-images.githubusercontent.com/30707349/77486023-e8e0a500-6deb-11ea-9bd4-d54c82e2fc16.png)

Note no change in the display when I select another cluster (cluster 156) or its nearest neighbor in Similarity View:
![Screenshot from 2020-03-24_cluster156inaccurate](https://user-images.githubusercontent.com/30707349/77486031-eaaa6880-6deb-11ea-911b-dd1fc9e7bfb7.png)

Note that there are no errors reported during this freeze using the `--debug` option:
![cluster156_debugoutput](https://user-images.githubusercontent.com/30707349/77486020-e8480e80-6deb-11ea-928d-183724f2e87a.png)

The gui is still operational, just doesn't update.  I'm using an NVIDIA GeForce RTX 2070 Super and nvidia driver 440.64. Any ideas?

**Comment by mari-sosa** [comment]
For now this seems to be resolved by deleting the file ~/.phy/TemplateGUI/state.json and re-launching phy.

**Comment by rossant** [comment]
okay feel free to reopen if the problems appears again
