### ISSUE TITLE
Phy2 freezzing

### ISSUE THREAD

**Issue by llobetv** [cortex-lab/phy#986]
Hi,
I try to install new phy and I encounter one big issue..., phy freeze one in ten when I select a new cluster and me my whole computer freeze until the timeout is over:

12:00:29.138 [D] supervisor:812       Clusters selected: [160] (140)
12:00:38.221 [E] qt:178               Timeout in _block().
12:00:59.935 [W] actions:213          Error when executing action Next best.
12:00:59.975 [D] actions:214          Traceback (most recent call last):
  File "/home/llobet/Documents/librairie/phy/phy/gui/actions.py", line 211, in wrapped
    return callback(*args)
  File "/home/llobet/miniconda3/envs/phy2/lib/python3.8/site-packages/phylib/utils/event.py", line 141, in emit
    res.append(f(sender, *args, **kwargs))
  File "/home/llobet/Documents/librairie/phy/phy/cluster/supervisor.py", line 847, in _on_action
    _block(lambda: not self._is_busy)
  File "/home/llobet/Documents/librairie/phy/phy/gui/qt.py", line 182, in _block
    raise RuntimeError("Timeout in _block().")
RuntimeError: Timeout in _block().

Have you an idea about the origin of the problem?

Best regards,
Victor Llobet

**Comment by llobetv** [comment]
When I increased timeout I got this: 

/home/llobet/Documents/librairie/phy/phy/cluster/views/correlogram.py:108: UserWarning: Persisting input arguments took 23.07s to run.
If this happens often in your code, it can cause performance problems 
(results will be correct in all cases). 
The reason for this is probably some large input arguments for a wrapped
 function (e.g. large strings).
THIS IS A JOBLIB ISSUE. If you can, kindly provide the joblib's team with an
 example so that they can fix the problem.
  ccg = self.correlograms(self.cluster_ids, self.bin_size, self.window_size)

**Comment by rossant** [comment]
Thanks for the details. This is really curious. Could you perhaps edit this correlogram.py file line 108 and add:

`print(self.cluster_ids, self.bin_size, self.window_size)`

**Comment by llobetv** [comment]
[64, 197] 0.0003 0.05
/home/llobet/Documents/librairie/phy/phy/cluster/views/correlogram.py:109: UserWarning: Persisting input arguments took 6.00s to run.
If this happens often in your code, it can cause performance problems 
(results will be correct in all cases). 
The reason for this is probably some large input arguments for a wrapped
 function (e.g. large strings).
THIS IS A JOBLIB ISSUE. If you can, kindly provide the joblib's team with an
 example so that they can fix the problem.
  ccg = self.correlograms(self.cluster_ids, self.bin_size, self.window_size)

**Comment by rossant** [comment]
Indeed... I don't understand why it takes a huge time (several seconds) to persist this input.
Does this persist if you launch the GUI with `--clear-cache --clear-state` at the end of the `phy...` command?

**Comment by llobetv** [comment]
It doesn't change anything... ccg = self.correlograms(self.cluster_ids, self.bin_size, self.window_size) still take age to run randomly (sometimes 60s)

**Comment by rossant** [comment]
What is your OS, RAM, hard drive characteristics (the one where the data is stored), its total size and free size? What is the size of the .phy subdirectory inside the data directory?

**Comment by llobetv** [comment]
Ubuntu 18.04
16 Gb
1To SSD, nearly empty
.phy/ size: 78.4Mo

**Comment by rossant** [comment]
Hmm. Go to `phy/apps/base.py` and comment line 822 (`'_get_correlograms'`)
Is it still slow?

**Comment by llobetv** [comment]
I found the issue, it was my fault...

I connect my ssd to an usb switch which should create bug when their was disk access... now that i connect it directly to my computer everything work well.

Sorry for that and thank you very much for your help.
Best,
Victor

**Comment by rossant** [comment]
good to know!

**Comment by TomBugnon** [comment]
@rossant could we please reopen this?

I regularly have the same issue:
![image](https://user-images.githubusercontent.com/14128078/123974706-1dfb8000-d9bd-11eb-82de-0e34e19d0e22.png)
![image](https://user-images.githubusercontent.com/14128078/123974753-29e74200-d9bd-11eb-9cf9-bab411e8fe83.png)

And sometimes (but not always) get the joblib message
```
The reason for this is probably some large input arguments for a wrapped
function (e.g. large strings).
THIS IS A JOBLIB ISSUE. If you can, kindly provide the joblib's team with an
example so that they can fix the problem.
```

This happens sparsely most of the time but now I'm curating a dataset with a massive number of spikes and I can't change the group of any cluster because of this...

I'm working on a server with huge RAM and CPU specs so I don't think that's the issue
