### ISSUE TITLE
Unable to open spike_clusters.npy or params.phy after installing Phy, due to OSError

### ISSUE THREAD

**Issue by zuhayousuf** [cortex-lab/phy#999]
So I followed the instructions on the Github repo for installing Phy up till here:
phy template-gui params.py

However, when I enter the line above, I get the following error in the picture attached. It is an OSError. Is there any way I can fix this? Any advice appreciated!

![OSError](https://user-images.githubusercontent.com/56175933/80562029-0933ee80-89ac-11ea-8f90-ef358b351d7a.png)

**Comment by zuhayousuf** [comment]
Some more comments: my raw flat binary file along with spike_clusters.npy and params.py are in the same folder as they're supposed to be. I'm still confused why it isn't working

**Comment by rossant** [comment]
spike_samples.npy is there too?

**Comment by zuhayousuf** [comment]
Not spike_samples.npy, but it has spike_times.npy

**Comment by zuhayousuf** [comment]
Okay, so the error on my end was that spike_times was not saved. Once I did that, it works. Thanks!
